### ISSUE TITLE
[mongodb]Failed to run tests after switching to jepsen0.1.4 or 0.1.5-SNAPSHOT => ClassCastException: java.lang.String cannot be cast to java.lang.Number

### ISSUE THREAD

**Issue by L-Evg** [jepsen-io/jepsen#165]
Hello.
 We are evaluating your brilliant tool as a base for some internal DBs related testing. We started with mongoDB and faced an issue described below.

Issue.
[mongodb module depends on jepsen0.1.3](https://github.com/jepsen-io/jepsen/blob/master/mongodb/project.clj) at the moment.  An attempt to upgrade to jepsen0.1.4 or to use jepsen0.1.5-SNAPSHOT entails no tests being run and 
`ERROR [2017-02-17 12:47:31,778] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
`

Steps.
0. Follow the instructions and set-up the docker based environment.
1. Login to "jepsen-control" node;
2. `cd mongodb` ;
3.  `vi project.clj` ;
4.  Change jepsen version to 0.1.4; 
5. Save the changes;
6. `lein deps`;
7. `lein run -- test`;

Expected.
Test execution goes the same way as in case on jepsen0.1.3

Actual.
Test execution starts. No tests are run. The execution ends with
`ERROR [2017-02-17 13:44:10,266] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
	at clojure.lang.Numbers.isPos(Numbers.java:96) ~[clojure-1.8.0.jar:na]
	at clojure.lang.Range.create(Range.java:80) ~[clojure-1.8.0.jar:na]
	at clojure.core$range.invokeStatic(core.clj:2922) ~[clojure-1.8.0.jar:na]
	at clojure.core$range.invoke(core.clj:2910) ~[clojure-1.8.0.jar:na]
	at jepsen.core$run_BANG_$fn__5985$fn__5986.invoke(core.clj:406) ~[jepsen-0.1.4.jar:na]
	at jepsen.core$run_BANG_$fn__5985.invoke(core.clj:392) ~[jepsen-0.1.4.jar:na]
	at jepsen.core$run_BANG_.invokeStatic(core.clj:375) ~[jepsen-0.1.4.jar:na]
	at jepsen.core$run_BANG_.invoke(core.clj:324) ~[jepsen-0.1.4.jar:na]
	at jepsen.mongodb.runner$test_cmd$fn__663.invoke(runner.clj:62) ~[classes/:na]
	at jepsen.cli$run_BANG_.invokeStatic(cli.clj:266) [jepsen-0.1.4.jar:na]
	at jepsen.cli$run_BANG_.invoke(cli.clj:196) [jepsen-0.1.4.jar:na]
	at jepsen.mongodb.runner$_main.invokeStatic(runner.clj:68) [classes/:na]
	at jepsen.mongodb.runner$_main.doInvoke(runner.clj:66) [classes/:na]
	at clojure.lang.RestFn.invoke(RestFn.java:408) [clojure-1.8.0.jar:na]
`
Please find the log enclosed.
[mongodb_tests_run_log.txt](https://github.com/jepsen-io/jepsen/files/783337/mongodb_tests_run_log.txt)

Note.
We would like to use our own ssh settings (i.e. no "root" user etc), so we had to modify jepsen.core|control.

**Comment by aphyr** [comment]
Without knowing what changes you've made to the source, there's no way for me to help figure out what's going on here. It may be worth looking at https://github.com/jepsen-io/mongodb/blob/master/project.clj, which uses 0.1.4-SNAPSHOT.

**Comment by L-Evg** [comment]
"Without knowing what changes you've made to the source, there's no way for me..." - yes, that is clear. However, even having no changes and using 0.1.4 we get the same exception.

**Comment by L-Evg** [comment]
We tried mongodb tests from that [other location](https://github.com/jepsen-io/mongodb/blob/master/project.clj) you pointed to and it seems working. Thank you!
