### ISSUE TITLE
error when following doc/db.md

### ISSUE THREAD

**Issue by UncP** [jepsen-io/jepsen#187]
I followed the doc/db.md exactly using docker, when running the etcd demo it produced error in `teardown` phase.

the command that caused error is this: 

> sudo -S -u root bash -c "cd /; start-stop-daemon --start --background --make-pidfile --remove-pidfile
--pidfile /opt/etcd/etcd.pid
--chdir /opt/etcd
--no-close --oknodo --exec /opt/etcdetcd --
--log-output stderr
--name n1
--listen-peer-urls http://n1:2380
--listen-client-urls http://n1:2379
--advertise-client-urls http://n1:2379
--initial-cluster-state new
--initial-advertise-peer-urls http://n1:2380
--initial-cluster n1=http://n1:2380,n2=http://n2:2380,n3=http://n3:2380,n4=http://n4:2380,n5=http://n5:2380 >> /opt/etcd/etcd.log 2>&1"

the log file in `n1` directory says this:`start-stop-daemon: unable to stat /opt/etcdetcd (No such file or directory)`

however when i use ssh to log into n1, the /opt/etcd does not exist, like it should.

how can i fix this?

> root@control:/jepsen/jepsen.etcdemo# lein run test
07:00:57.636 [main] INFO  jepsen.cli - Test options:
 {:concurrency 5,
 :test-count 1,
 :time-limit 60,
 :nodes [:n1 :n2 :n3 :n4 :n5],
 :ssh
 {:username "root",
  :password "root",
  :strict-host-key-checking false,
  :private-key-path nil}}
INFO [2017-07-14 07:00:58,463] jepsen node n5 - jepsen.os.debian :n5 setting up debian
INFO [2017-07-14 07:00:58,463] jepsen node n3 - jepsen.os.debian :n3 setting up debian
INFO [2017-07-14 07:00:58,464] jepsen node n4 - jepsen.os.debian :n4 setting up debian
INFO [2017-07-14 07:00:58,465] jepsen node n2 - jepsen.os.debian :n2 setting up debian
INFO [2017-07-14 07:00:58,471] jepsen node n1 - jepsen.os.debian :n1 setting up debian
INFO [2017-07-14 07:00:59,225] jepsen node n4 - jepsen.etcdemo :n4 tearing down etcd
INFO [2017-07-14 07:00:59,225] jepsen node n5 - jepsen.etcdemo :n5 tearing down etcd
INFO [2017-07-14 07:00:59,225] jepsen node n3 - jepsen.etcdemo :n3 tearing down etcd
INFO [2017-07-14 07:00:59,226] jepsen node n2 - jepsen.etcdemo :n2 tearing down etcd
INFO [2017-07-14 07:00:59,226] jepsen node n1 - jepsen.etcdemo :n1 tearing down etcd
INFO [2017-07-14 07:00:59,227] jepsen node n5 - jepsen.control.util Stopping /opt/etcdetcd
INFO [2017-07-14 07:00:59,227] jepsen node n4 - jepsen.control.util Stopping /opt/etcdetcd
INFO [2017-07-14 07:00:59,227] jepsen node n3 - jepsen.control.util Stopping /opt/etcdetcd
INFO [2017-07-14 07:00:59,228] jepsen node n2 - jepsen.control.util Stopping /opt/etcdetcd
INFO [2017-07-14 07:00:59,228] jepsen node n1 - jepsen.control.util Stopping /opt/etcdetcd
INFO [2017-07-14 07:00:59,535] jepsen node n2 - jepsen.etcdemo :n2 installing etcd v3.1.5
INFO [2017-07-14 07:00:59,535] jepsen node n1 - jepsen.etcdemo :n1 installing etcd v3.1.5
INFO [2017-07-14 07:00:59,542] jepsen node n4 - jepsen.etcdemo :n4 installing etcd v3.1.5
INFO [2017-07-14 07:00:59,550] jepsen node n3 - jepsen.etcdemo :n3 installing etcd v3.1.5
INFO [2017-07-14 07:00:59,556] jepsen node n5 - jepsen.etcdemo :n5 installing etcd v3.1.5
INFO [2017-07-14 07:01:02,096] jepsen node n4 - jepsen.control.util starting etcdetcd
INFO [2017-07-14 07:01:02,098] jepsen node n3 - jepsen.control.util starting etcdetcd
INFO [2017-07-14 07:01:02,166] jepsen node n1 - jepsen.control.util starting etcdetcd
INFO [2017-07-14 07:01:02,168] jepsen node n2 - jepsen.control.util starting etcdetcd
INFO [2017-07-14 07:01:02,187] jepsen node n5 - jepsen.control.util starting etcdetcd
INFO [2017-07-14 07:01:02,271] jepsen test runner - jepsen.core Snarfing log files
INFO [2017-07-14 07:01:02,279] jepsen node n5 - jepsen.core downloading /opt/etcd/etcd.log to etcd.log
INFO [2017-07-14 07:01:02,279] jepsen node n4 - jepsen.core downloading /opt/etcd/etcd.log to etcd.log
INFO [2017-07-14 07:01:02,279] jepsen node n1 - jepsen.core downloading /opt/etcd/etcd.log to etcd.log
INFO [2017-07-14 07:01:02,280] jepsen node n3 - jepsen.core downloading /opt/etcd/etcd.log to etcd.log
INFO [2017-07-14 07:01:02,280] jepsen node n2 - jepsen.core downloading /opt/etcd/etcd.log to etcd.log
INFO [2017-07-14 07:01:02,339] jepsen node n5 - jepsen.etcdemo :n5 tearing down etcd
INFO [2017-07-14 07:01:02,339] jepsen node n3 - jepsen.etcdemo :n3 tearing down etcd
INFO [2017-07-14 07:01:02,339] jepsen node n2 - jepsen.etcdemo :n2 tearing down etcd
INFO [2017-07-14 07:01:02,339] jepsen node n1 - jepsen.etcdemo :n1 tearing down etcd
INFO [2017-07-14 07:01:02,339] jepsen node n4 - jepsen.etcdemo :n4 tearing down etcd
INFO [2017-07-14 07:01:02,340] jepsen node n5 - jepsen.control.util Stopping /opt/etcdetcd
INFO [2017-07-14 07:01:02,340] jepsen node n3 - jepsen.control.util Stopping /opt/etcdetcd
INFO [2017-07-14 07:01:02,340] jepsen node n2 - jepsen.control.util Stopping /opt/etcdetcd
INFO [2017-07-14 07:01:02,340] jepsen node n1 - jepsen.control.util Stopping /opt/etcdetcd
INFO [2017-07-14 07:01:02,340] jepsen node n4 - jepsen.control.util Stopping /opt/etcdetcd
ERROR [2017-07-14 07:01:03,190] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
java.util.concurrent.ExecutionException: java.lang.RuntimeException: sudo -S -u root bash -c "cd /; start-stop-daemon --start --background --make-pidfile --remove-pidfile --pidfile /opt/etcd/etcd.pid --chdir /opt/etcd --no-close --oknodo --exec /opt/etcdetcd -- --log-output stderr --name n1 --listen-peer-urls http://n1:2380 --listen-client-urls http://n1:2379 --advertise-client-urls http://n1:2379 --initial-cluster-state new --initial-advertise-peer-urls http://n1:2380 --initial-cluster n1=http://n1:2380,n2=http://n2:2380,n3=http://n3:2380,n4=http://n4:2380,n5=http://n5:2380 >> /opt/etcd/etcd.log 2>&1" returned non-zero exit status 2 on n1. STDOUT:
STDERR:
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_131]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_131]
	at clojure.core$deref_future.invokeStatic(core.clj:2208) ~[clojure-1.8.0.jar:na]
	at clojure.core$future_call$reify__6962.deref(core.clj:6688) ~[clojure-1.8.0.jar:na]
	at clojure.core$deref.invokeStatic(core.clj:2228) ~[clojure-1.8.0.jar:na]
	at clojure.core$deref.invoke(core.clj:2214) ~[clojure-1.8.0.jar:na]
	at clojure.core$map$fn__4785.invoke(core.clj:2646) ~[clojure-1.8.0.jar:na]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.8.0.jar:na]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.8.0.jar:na]
	at clojure.lang.RT.seq(RT.java:521) ~[clojure-1.8.0.jar:na]
	at clojure.core$seq__4357.invokeStatic(core.clj:137) ~[clojure-1.8.0.jar:na]
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24) ~[clojure-1.8.0.jar:na]
	at clojure.core.protocols$fn__6738.invokeStatic(protocols.clj:75) ~[clojure-1.8.0.jar:na]
	at clojure.core.protocols$fn__6738.invoke(protocols.clj:75) ~[clojure-1.8.0.jar:na]
	at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13) ~[clojure-1.8.0.jar:na]
	at clojure.core$reduce.invokeStatic(core.clj:6545) ~[clojure-1.8.0.jar:na]
	at clojure.core$into.invokeStatic(core.clj:6610) ~[clojure-1.8.0.jar:na]
	at clojure.core$into.invoke(core.clj:6604) ~[clojure-1.8.0.jar:na]
	at jepsen.control$on_nodes.invokeStatic(control.clj:319) ~[jepsen-0.1.4.jar:na]
	at jepsen.control$on_nodes.invoke(control.clj:310) ~[jepsen-0.1.4.jar:na]
	at jepsen.core$run_BANG_$fn__5985$fn__5986.invoke(core.clj:404) ~[jepsen-0.1.4.jar:na]
	at jepsen.core$run_BANG_$fn__5985.invoke(core.clj:392) ~[jepsen-0.1.4.jar:na]
	at jepsen.core$run_BANG_.invokeStatic(core.clj:375) ~[jepsen-0.1.4.jar:na]
	at jepsen.core$run_BANG_.invoke(core.clj:324) ~[jepsen-0.1.4.jar:na]
	at jepsen.cli$single_test_cmd$fn__6627.invoke(cli.clj:322) ~[jepsen-0.1.4.jar:na]
	at jepsen.cli$run_BANG_.invokeStatic(cli.clj:266) [jepsen-0.1.4.jar:na]
	at jepsen.cli$run_BANG_.invoke(cli.clj:196) [jepsen-0.1.4.jar:na]
	at jepsen.etcdemo$_main.invokeStatic(etcdemo.clj:91) [na:na]
	at jepsen.etcdemo$_main.doInvoke(etcdemo.clj:87) [na:na]
	at clojure.lang.RestFn.invoke(RestFn.java:408) [clojure-1.8.0.jar:na]
	at clojure.lang.Var.invoke(Var.java:379) [clojure-1.8.0.jar:na]
	at user$eval5.invokeStatic(form-init4924047095922095539.clj:1) [na:na]
	at user$eval5.invoke(form-init4924047095922095539.clj:1) [na:na]
	at clojure.lang.Compiler.eval(Compiler.java:6927) [clojure-1.8.0.jar:na]
	at clojure.lang.Compiler.eval(Compiler.java:6917) [clojure-1.8.0.jar:na]
	at clojure.lang.Compiler.load(Compiler.java:7379) [clojure-1.8.0.jar:na]
	at clojure.lang.Compiler.loadFile(Compiler.java:7317) [clojure-1.8.0.jar:na]
	at clojure.main$load_script.invokeStatic(main.clj:275) [clojure-1.8.0.jar:na]
	at clojure.main$init_opt.invokeStatic(main.clj:277) [clojure-1.8.0.jar:na]
	at clojure.main$init_opt.invoke(main.clj:277) [clojure-1.8.0.jar:na]
	at clojure.main$initialize.invokeStatic(main.clj:308) [clojure-1.8.0.jar:na]
	at clojure.main$null_opt.invokeStatic(main.clj:342) [clojure-1.8.0.jar:na]
	at clojure.main$null_opt.invoke(main.clj:339) [clojure-1.8.0.jar:na]
	at clojure.main$main.invokeStatic(main.clj:421) [clojure-1.8.0.jar:na]
	at clojure.main$main.doInvoke(main.clj:384) [clojure-1.8.0.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:421) [clojure-1.8.0.jar:na]
	at clojure.lang.Var.invoke(Var.java:383) [clojure-1.8.0.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:156) [clojure-1.8.0.jar:na]
	at clojure.lang.Var.applyTo(Var.java:700) [clojure-1.8.0.jar:na]
	at clojure.main.main(main.java:37) [clojure-1.8.0.jar:na]
Caused by: java.lang.RuntimeException: sudo -S -u root bash -c "cd /; start-stop-daemon --start --background --make-pidfile --remove-pidfile --pidfile /opt/etcd/etcd.pid --chdir /opt/etcd --no-close --oknodo --exec /opt/etcdetcd -- --log-output stderr --name n1 --listen-peer-urls http://n1:2380 --listen-client-urls http://n1:2379 --advertise-client-urls http://n1:2379 --initial-cluster-state new --initial-advertise-peer-urls http://n1:2380 --initial-cluster n1=http://n1:2380,n2=http://n2:2380,n3=http://n3:2380,n4=http://n4:2380,n5=http://n5:2380 >> /opt/etcd/etcd.log 2>&1" returned non-zero exit status 2 on n1. STDOUT:
STDERR:
	at jepsen.control$throw_on_nonzero_exit.invokeStatic(control.clj:112) ~[jepsen-0.1.4.jar:na]
	at jepsen.control$throw_on_nonzero_exit.invoke(control.clj:105) ~[jepsen-0.1.4.jar:na]
	at jepsen.control$exec_STAR_.invokeStatic(control.clj:144) ~[jepsen-0.1.4.jar:na]
	at jepsen.control$exec_STAR_.doInvoke(control.clj:141) ~[jepsen-0.1.4.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) [clojure-1.8.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:646) ~[clojure-1.8.0.jar:na]
	at clojure.core$apply.invoke(core.clj:641) ~[clojure-1.8.0.jar:na]
	at jepsen.control$exec.invokeStatic(control.clj:160) ~[jepsen-0.1.4.jar:na]
	at jepsen.control$exec.doInvoke(control.clj:154) ~[jepsen-0.1.4.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) [clojure-1.8.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:654) ~[clojure-1.8.0.jar:na]
	at clojure.core$apply.doInvoke(core.clj:641) ~[clojure-1.8.0.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:2183) [clojure-1.8.0.jar:na]
	at jepsen.control.util$start_daemon_BANG_.invokeStatic(util.clj:158) ~[na:na]
	at jepsen.control.util$start_daemon_BANG_.doInvoke(util.clj:148) ~[na:na]
	at clojure.lang.RestFn.invoke(RestFn.java:2835) [clojure-1.8.0.jar:na]
	at jepsen.etcdemo$db$reify__435.setup_BANG_(etcdemo.clj:51) ~[na:na]
	at jepsen.db$cycle_BANG_.invokeStatic(db.clj:25) ~[jepsen-0.1.4.jar:na]
	at jepsen.db$cycle_BANG_.invoke(db.clj:20) ~[jepsen-0.1.4.jar:na]
	at clojure.core$partial$fn__4759.invoke(core.clj:2516) ~[clojure-1.8.0.jar:na]
	at jepsen.control$on_nodes$fn__4083.invoke(control.clj:318) ~[jepsen-0.1.4.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:154) [clojure-1.8.0.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.8.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:646) ~[clojure-1.8.0.jar:na]
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881) ~[clojure-1.8.0.jar:na]
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881) ~[clojure-1.8.0.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:142) [clojure-1.8.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:650) ~[clojure-1.8.0.jar:na]
	at clojure.core$bound_fn_STAR_$fn__4671.doInvoke(core.clj:1911) ~[clojure-1.8.0.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:408) [clojure-1.8.0.jar:na]
	at jepsen.util$real_pmap$launcher__3249$fn__3250.invoke(util.clj:47) ~[jepsen-0.1.4.jar:na]
	at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938) ~[clojure-1.8.0.jar:na]
	at clojure.lang.AFn.call(AFn.java:18) [clojure-1.8.0.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]

**Comment by vjuranek** [comment]
There is missing `/` in `etcd` binary path in doc snippet. However, if `/opt/etcd` is missing on your test nodes, it looks like there was some other problem with downloading etcd tarball. I checked that https://storage.googleapis.com/etcd/v3.1.5/etcd-v3.1.5-linux-amd64.tar.gz works, so maybe (this is just my guess) you have again some problem with DNS resolution which causes that download and installation of etcd silently fails?

Also, if you was able to setup and run the cluster, maybe you can consider closing #185 ?

**Comment by UncP** [comment]
in etcd test suite etcd/src/jepsen/etcd.clj, it is `(def binary  "etcd")`,
in your doc/db.md, it is `(def binary  (str dir "etcd"))`,
i think maybe  in your doc it should be `(def binary  "etcd")`.

**Comment by vjuranek** [comment]
well, it shouldn't matter, both should work, but agree that what you proposed is more clear and consistent with `etcd/src/jepsen/etcd.clj`, so I've changes my PR accordingly.

**Comment by UncP** [comment]
i just tried `(def binary "etcd")`, it worked.
i will close this issue.
