### ISSUE TITLE
[Question] Is this possible to call jepsen.control/exec inside the jepsen.client/Client's setup! function?

### ISSUE THREAD

**Issue by yyh-graphsql** [jepsen-io/jepsen#212]
Hi, I have some specific setups to do for different client type. What I do is put the setup works inside the client/Client's setup! function. I also use client id to run my setup only once. My setup is basically to run a command. When I call a command like (jepsen.control/exec :ls) inside the client/Client's setup!. I got this:
```
INFO [2017-10-26 15:26:31,944] clojure-agent-send-off-pool-1 -.gse Setup VertexOpClient on m3 with vertex batch count 512
INFO [2017-10-26 15:26:31,944] clojure-agent-send-off-pool-5 -.gse Setup VertexOpClient on m3 with vertex batch count 512
INFO [2017-10-26 15:26:31,944] clojure-agent-send-off-pool-0 -.gse Setup VertexOpClient on m1 with vertex batch count 512
INFO [2017-10-26 15:26:31,944] clojure-agent-send-off-pool-6 -.gse Setup VertexOpClient on m1 with vertex batch count 512
INFO [2017-10-26 15:26:31,944] clojure-agent-send-off-pool-4 -.gse Setup VertexOpClient on m2 with vertex batch count 512
INFO [2017-10-26 15:26:31,944] clojure-agent-send-off-pool-2 -.gse Setup VertexOpClient on m2 with vertex batch count 512
INFO [2017-10-26 15:26:31,944] clojure-agent-send-off-pool-3 -.gse Setup VertexOpClient on m1 with vertex batch count 512
INFO [2017-10-26 15:26:31,944] clojure-agent-send-off-pool-8 -.gse Setup VertexOpClient on m3 with vertex batch count 512
INFO [2017-10-26 15:26:31,946] clojure-agent-send-off-pool-7 -.gse Setup VertexOpClient on m2 with vertex batch count 512
INFO [2017-10-26 15:26:31,950] clojure-agent-send-off-pool-2 -.gse Teardown VertexOpClient on
INFO [2017-10-26 15:26:31,950] clojure-agent-send-off-pool-4 -.gse Teardown VertexOpClient on
INFO [2017-10-26 15:26:31,950] clojure-agent-send-off-pool-8 -.gse Teardown VertexOpClient on
INFO [2017-10-26 15:26:31,950] clojure-agent-send-off-pool-3 -.gse Teardown VertexOpClient on
INFO [2017-10-26 15:26:31,950] clojure-agent-send-off-pool-7 -.gse Teardown VertexOpClient on
INFO [2017-10-26 15:26:31,950] clojure-agent-send-off-pool-5 -.gse Teardown VertexOpClient on
INFO [2017-10-26 15:26:31,950] clojure-agent-send-off-pool-6 -.gse Teardown VertexOpClient on
INFO [2017-10-26 15:26:31,950] clojure-agent-send-off-pool-0 -.gse Teardown VertexOpClient on
ERROR [2017-10-26 15:26:31,980] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
java.lang.NullPointerException: null
        at jepsen.control$ssh_STAR_$fn__4014.invoke(control.clj:129) ~[jepsen-0.1.5.jar:na]
        at jepsen.control$ssh_STAR_.invokeStatic(control.clj:129) ~[jepsen-0.1.5.jar:na]
        at jepsen.control$ssh_STAR_.invoke(control.clj:125) ~[jepsen-0.1.5.jar:na]
        at jepsen.control$exec_STAR_.invokeStatic(control.clj:145) ~[jepsen-0.1.5.jar:na]
        at jepsen.control$exec_STAR_.doInvoke(control.clj:142) ~[jepsen-0.1.5.jar:na]
        at clojure.lang.RestFn.applyTo(RestFn.java:137) ~[clojure-1.8.0.jar:na]
        at clojure.core$apply.invokeStatic(core.clj:646) ~[clojure-1.8.0.jar:na]
        at clojure.core$apply.invoke(core.clj:641) ~[clojure-1.8.0.jar:na]
        at jepsen.control$exec.invokeStatic(control.clj:161) ~[jepsen-0.1.5.jar:na]
        at jepsen.control$exec.doInvoke(control.clj:155) ~[jepsen-0.1.5.jar:na]
        at clojure.lang.RestFn.invoke(RestFn.java:436) ~[clojure-1.8.0.jar:na]
        at.gsql.VertexReqHelper.gsql_cleanup_BANG_(gsql.clj:52) ~[na:na]
        at.gsql.VertexReqHelper.gsql_setup_BANG_(gsql.clj:57) ~[na:na]
        at.gse.VertexOpClient.setup_BANG_(gse.clj:74) ~[na:na]
        at jepsen.core$run_case_BANG_$fn__5962.invoke(core.clj:287) ~[jepsen-0.1.5.jar:na]
        at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[clojure-1.8.0.jar:na]
        at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.8.0.jar:na]
        at clojure.core$apply.invokeStatic(core.clj:646) ~[clojure-1.8.0.jar:na]
        at clojure.core$apply.invoke(core.clj:641) ~[clojure-1.8.0.jar:na]
        at jepsen.util$fcatch$wrapper__3244.doInvoke(util.clj:27) ~[jepsen-0.1.5.jar:na]
        at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.8.0.jar:na]
        at jepsen.util$real_pmap$launcher__3249$fn__3250.invoke(util.clj:47) ~[jepsen-0.1.5.jar:na]
        at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938) ~[clojure-1.8.0.jar:na]
        at clojure.lang.AFn.call(AFn.java:18) ~[clojure-1.8.0.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_144]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_144]
```

**Comment by aphyr** [comment]
Yes; you'll want to pick a node or nodes to run on, then use jepsen.control/on-nodes or similar to run your code on a particular node.

**Comment by yyh-graphsql** [comment]
@aphyr Have a followup question. How can I synchronize the client setup!. 
When I called the (jepsen/synchronize test) it will hang for some reason.

**Comment by yyh-graphsql** [comment]
Got the following error when change from jepsen 0.1.5 to 0.1.6
```
java.lang.IllegalArgumentException: No implementation of method: :check of protocol: #'jepsen.checker/Checker found for class: jepsen.checker$set
  at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:568) ~[clojure-1.8.0.jar:na]
  at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:560) ~[clojure-1.8.0.jar:na]
  at jepsen.checker$fn__3108$G__3103__3121.invoke(checker.clj:46) ~[jepsen-0.1.6.jar:na]
  at jepsen.checker$check_safe.invokeStatic(checker.clj:70) [jepsen-0.1.6.jar:na]
  at jepsen.checker$check_safe.invoke(checker.clj:63) [jepsen-0.1.6.jar:na]
  at jepsen.checker$compose$reify__3207$fn__3209.invoke(checker.clj:386) [jepsen-0.1.6.jar:na]
  at clojure.core$pmap$fn__6970$fn__6971.invoke(core.clj:6736) [clojure-1.8.0.jar:na]
  at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938) [clojure-1.8.0.jar:na]
  at clojure.lang.AFn.call(AFn.java:18) [clojure-1.8.0.jar:na]
  at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_144]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
  at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
INFO [2017-10-28 21:35:53,366] jepsen test runner - jepsen.core Analysis complete
INFO [2017-10-28 21:35:53,418] jepsen results - jepsen.store Wrote /home/graphsql/yihao/tiger/bigtest/tests/ha_regression/jepsen-tigergraph/store/Vertex-Sets/20171028T213521.000-0700/results.edn
INFO [2017-10-28 21:35:53,475] main - jepsen.core {:timeline {:valid? true},
```

**Comment by yyh-graphsql** [comment]
I also get this exception after I use jepsen 0.16 (in 0.15 on-nodes is worked for specific nodes):
```
WARN [2017-10-30 00:36:51,577] clojure-agent-send-off-pool-28 - jepsen.checker Error while checking history:
java.lang.IllegalArgumentException: No implementation of method: :check of protocol: #'jepsen.checker/Checker found for class: jepsen.checker$set
        at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:568) ~[clojure-1.8.0.jar:na]
        at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:560) ~[clojure-1.8.0.jar:na]
        at jepsen.checker$fn__3108$G__3103__3121.invoke(checker.clj:46) ~[jepsen-0.1.6.jar:na]
        at jepsen.checker$check_safe.invokeStatic(checker.clj:70) [jepsen-0.1.6.jar:na]
        at jepsen.checker$check_safe.invoke(checker.clj:63) [jepsen-0.1.6.jar:na]
        at jepsen.checker$compose$reify__3207$fn__3209.invoke(checker.clj:386) [jepsen-0.1.6.jar:na]
        at clojure.core$pmap$fn__6970$fn__6971.invoke(core.clj:6736) [clojure-1.8.0.jar:na]
        at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938) [clojure-1.8.0.jar:na]
        at clojure.lang.AFn.call(AFn.java:18) [clojure-1.8.0.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
```

**Comment by aphyr** [comment]
In 0.1.6, `checker/set` is a function, not a checker. The exception says that you can't call `check` on that function.

**Comment by yyh-graphsql** [comment]
@aphyr  The following is the client setup code
```
(setup! [this test node]
    (let [batch (-> this :gsql-helper :vertex-batch-write-cnt)]
      (info (str "Setup VertexOpClient on " node " with vertex batch count "
                 batch))
      ; clear graph store and reset schema
      (let [cnt (-> test :nodes count)
            agent-node (:agent-node test)]
        (when (and (= node agent-node)
                   (= (swap! identify inc) 1))
          (info "Creating graph schema for VertexOpClient on " node)
          (c/on-nodes test
                      [agent-node]
                      #(let [a %1 b %2] (gsql/gsql-setup! (:gsql-helper this))))
          (info "Created graph schema for VertexOpClient")))
      ; synchronize all node after create graph schema
      (.await ^CyclicBarrier (:barrier-for-clients test))
      (assoc this :node node :batch batch))
  )
```
and gsql-setup!:
```
  (gsql-cleanup! [this]
    (info "Drop graph schema.")
    (c/trace (c/exec :ls))
    (info "Dropped graph schema."))

  ;Install the new schema/query in $gsql-file-path. Throw exception when gsql
  ;fails.
  (gsql-setup! [this]
    (gsql-cleanup! this)
    (let [gsql-file-name (:gsql-file-name this)]
      (info "gsql " gsql-file-name)
      (c/trace (c/upload (str resource-path "/" gsql-file-name)
                         target-resource-path))
      (c/trace (c/exec :gsql (str target-resource-path
                                  gsql-file-name))))) 
```

After I ran the test, it gave the following log and hangs forever:
```
INFO [2017-12-12 22:43:33,017] jepsen node 192.168.55.81 - tigergraph.gsql Drop graph schema.
INFO [2017-12-12 22:43:33,018] jepsen node 192.168.55.81 - jepsen.control {:cmd cd /; ls}
INFO [2017-12-12 22:43:38,815] jepsen node 192.168.55.81 - tigergraph.gsql Dropped graph schema.
INFO [2017-12-12 22:43:38,816] jepsen node 192.168.55.81 - tigergraph.gsql gsql 1
WARN [2017-12-12 22:43:38,831] jepsen node 192.168.55.81 - jepsen.control Encountered error with conn [:control "192.168.55.81"]; reopening
```
Can you give me some hint on this? I want to know what's going on or how to debug this?

**Comment by aphyr** [comment]
No idea, sorry. Reopening is a normal error message when there are connection hiccups with an SSH conn.

**Comment by yyh-graphsql** [comment]
Thanks, at least I can make sure this is a ssh connection issue.

**Comment by aphyr** [comment]
I... wouldn't necessarily assume that. Jstack to find out.

**Comment by yyh-graphsql** [comment]
I don’t know the logic but seems I found the reason. If the command is not exist, the command exec would hang.

**Comment by aphyr** [comment]
Exec doesn't hang in that case; it should throw. I think you accidentally allowed a deadlock in your setup code.
