### ISSUE TITLE
com.jcraft.jsch.JSchException: Auth fail

### ISSUE THREAD

**Issue by jvrao** [jepsen-io/jepsen#236]
I am using GCP; I can ssh fine, but when I try to use Jepsen I see the following error
Not sure why it is taking username and password; but I tried with default which was taking username root, and also tried with --username vjujjuri; both fail with same stack. 

{:nodes-file "nodes.latest",
 :concurrency 5,
 :bookkeeper-tarball
 "http://apache.rediris.es/bookkeeper/bookkeeper-4.6.0/bookkeeper-server-4.6.0-bin.tar.gz",
 :ssh
 {:username "vjujjuri",
  :password "root",
  :strict-host-key-checking false,
  :private-key-path nil},
 :register-service-uberjar
 "https://github.com/ivankelly/register-service/releases/download/v0.2.0/register-service-0.2.0-standalone.jar",
 :requests-per-second 1,
 :nodes
 ["35.190.181.x"
  "35.196.219.x"
  "35.196.158.x"
  "35.227.91.x"
  "35.185.124.x"],
 :test-count 1,
 :time-limit 60}

ERROR [2018-02-02 18:04:16,978] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:512) ~[jsch-0.1.53.jar:na]
	at com.jcraft.jsch.Session.connect(Session.java:183) ~[jsch-0.1.53.jar:na]
	at clj_ssh.ssh$fn__3687.invokeStatic(ssh.clj:118) ~[jepsen-0.1.4.jar:na]
	at clj_ssh.ssh$fn__3687.invoke(ssh.clj:115) ~[jepsen-0.1.4.jar:na]
	at clj_ssh.ssh.protocols$fn__3645$G__3612__3654.invoke(protocols.clj:4) ~[jepsen-0.1.4.jar:na]
	at clj_ssh.ssh$connect.invokeStatic(ssh.clj:401) ~[jepsen-0.1.4.jar:na]
	at clj_ssh.ssh$connect.invoke(ssh.clj:397) ~[jepsen-0.1.4.jar:na]
	at jepsen.control$clj_ssh_session.invokeStatic(control.clj:241) ~[jepsen-0.1.4.jar:na]
	at jepsen.control$clj_ssh_session.invoke(control.clj:233) ~[jepsen-0.1.4.jar:na]
	at jepsen.control$session$fn__4070.invoke(control.clj:253) ~[jepsen-0.1.4.jar:na]
	at jepsen.reconnect$open_BANG_$fn__3965.invoke(reconnect.clj:59) ~[jepsen-0.1.4.jar:na]
	at jepsen.reconnect$open_BANG_.invokeStatic(reconnect.clj:57) ~[jepsen-0.1.4.jar:na]
	at jepsen.reconnect$open_BANG_.invoke(reconnect.clj:54) ~[jepsen-0.1.4.jar:na]
	at jepsen.control$session.invokeStatic(control.clj:252) ~[jepsen-0.1.4.jar:na]
	at jepsen.control$session.invoke(control.clj:249) ~[jepsen-0.1.4.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[clojure-1.8.0.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.8.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:646) ~[clojure-1.8.0.jar:na]
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881) ~[clojure-1.8.0.jar:na]
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881) ~[clojure-1.8.0.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:142) ~[clojure-1.8.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:650) ~[clojure-1.8.0.jar:na]
	at clojure.core$bound_fn_STAR_$fn__4671.doInvoke(core.clj:1911) ~[clojure-1.8.0.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) ~[clojure-1.8.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:646) ~[clojure-1.8.0.jar:na]
	at clojure.core$apply.invoke(core.clj:641) ~[clojure-1.8.0.jar:na]
	at jepsen.util$fcatch$wrapper__3244.doInvoke(util.clj:27) ~[jepsen-0.1.4.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.8.0.jar:na]
	at jepsen.util$real_pmap$launcher__3249$fn__3250.invoke(util.clj:47) ~[jepsen-0.1.4.jar:na]
	at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938) ~[clojure-1.8.0.jar:na]
	at clojure.lang.AFn.call(AFn.java:18) ~[clojure-1.8.0.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]

**Comment by graysonchao** [comment]
I'm seeing the same issue with a Dockerized setup, can confirm that regular old SSH works from the control node to db nodes. I'll post more details and log my troubleshooting findings when I get home from class.

**Comment by aphyr** [comment]
Might be worth checking that your SSH agent is running locally and is providing the appropriate keys for that node?

**Comment by graysonchao** [comment]
Thanks for following up! Looks like that was my problem, at least. I was confused for a while because I had experimentally forced the root password and supplied it with --password, and that didn't seem to help. Plus, [the tutum-debian image I adapted my custom one from](https://github.com/tutumcloud/tutum-debian/blob/master/jessie/Dockerfile) looks like it enables passwordless root login in sshd_config. For future readers, the fix was to run `ssh-add` before `lein run test` on the control node.

**Comment by graysonchao** [comment]
...Also just wanna say, long time fan, first time caller, I love the Jepsen blog and your Twitter. ☺️

**Comment by aphyr** [comment]
You're welcome. There's expanded SSH help in the README now too: e9db418
