### ISSUE TITLE
Dgraph: Unhandled exeptions in Alter command cause Nemesis to fail

### ISSUE THREAD

**Issue by manishrjain** [jepsen-io/jepsen#272]
```
io.grpc.StatusRuntimeException: UNKNOWN: Unable to abort transactions
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:221) ~[grpc-stub-1.10.0.jar:1.10.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:202) ~[grpc-stub-1.10.0.jar:1.10.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:131) ~[grpc-stub-1.10.0.jar:1.10.0]
	at io.dgraph.DgraphGrpc$DgraphBlockingStub.alter(DgraphGrpc.java:425) ~[dgraph4j-1.3.0.jar:na]
	at io.dgraph.DgraphClient.alter(DgraphClient.java:119) ~[dgraph4j-1.3.0.jar:na]
	at jepsen.dgraph.client$alter_schema_BANG_$fn__241.invoke(client.clj:171) ~[na:na]
	at jepsen.dgraph.client$alter_schema_BANG_.invokeStatic(client.clj:171) ~[classes/:na]
	at jepsen.dgraph.client$alter_schema_BANG_.doInvoke(client.clj:165) ~[classes/:na]
```

**Comment by manishrjain** [comment]
Think this was resolved.
