### ISSUE TITLE
Error client/invoke! to return Error

### ISSUE THREAD

**Issue by fengchuimailang** [jepsen-io/jepsen#280]
when I learn jepsen by following the tutorial 3.Writing a Client  an error occurred。 but I don‘t how to fix it。

The Error：
```
java.lang.AssertionError: Assert failed: Expected client/invoke! to return a map with :type :ok, :fail, or :info, but received {:time 274103600} instead
(or (= t :ok) (= t :fail) (= t :info))
	at jepsen.core$invoke_op_BANG_.invokeStatic(core.clj:291) ~[jepsen-0.1.10.jar:na]
	at jepsen.core$invoke_op_BANG_.invoke(core.clj:267) ~[jepsen-0.1.10.jar:na]
	at jepsen.core.ClientWorker.run_worker_BANG_(core.clj:403) ~[jepsen-0.1.10.jar:na]
	at jepsen.core$do_worker_BANG_.invokeStatic(core.clj:187) ~[jepsen-0.1.10.jar:na]
	at jepsen.core$do_worker_BANG_.invoke(core.clj:171) ~[jepsen-0.1.10.jar:na]
	at jepsen.core$run_workers_BANG_$fn__4598$fn__4599.invoke(core.clj:240) ~[jepsen-0.1.10.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:152) ~[clojure-1.9.0.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.9.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:657) ~[clojure-1.9.0.jar:na]
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1965) ~[clojure-1.9.0.jar:na]
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1965) ~[clojure-1.9.0.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:425) ~[clojure-1.9.0.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:156) ~[clojure-1.9.0.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:132) ~[clojure-1.9.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:661) ~[clojure-1.9.0.jar:na]
	at clojure.core$bound_fn_STAR_$fn__5471.doInvoke(core.clj:1995) ~[clojure-1.9.0.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:397) ~[clojure-1.9.0.jar:na]
	at clojure.lang.AFn.run(AFn.java:22) ~[clojure-1.9.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
```

And the Code
```
(ns jepsen.etcdemo
  (:require [clojure.tools.logging :refer :all]
            [clojure.string :as str]
            [verschlimmbesserung.core :as v]
            [jepsen [cli :as cli]
                    [client :as client]
                    [control :as c]
                    [db :as db]
                    [generator :as gen]
                    [tests :as tests]]
            [jepsen.control.util :as cu]
            [jepsen.os.debian :as debian]))


(def dir "/opt/etcd")
(def binary "etcd")
(def logfile (str dir "/etcd.log"))
(def pidfile (str dir "/etcd.pid"))

(defn node-url
  "An HTTP url for connecting to a node on a particular port."
  [node port]
  (str "http://" (name node) ":" port))

(defn peer-url
  "The HTTP url for other peers to talk to a node."
  [node]
  (node-url node 2380))

(defn client-url
  "The HTTP url Clients use to talk to a node."
  [node]
  (node-url node 2379))

(defn initial-cluster
  "Constructs an initial cluster string for a test, like
  \" foo=foo:2380,bar=bar:2380,...\""
  [test]
  (->> (:nodes test)
       (map (fn [node]
              (str node "=" (peer-url node))))
       (str/join ",")))


(defn db
  "Etcd DB for a particular version."
  [version]
  (reify db/DB 
    (setup! [_ test node]
      (info node "installing etcd" version)
      (c/su
        (let [url (str "github.com/coreos/etcd/releases/download/" version
                       "/etcd-" version "-linux-amd64.tar.gz")]
          (cu/install-archive! url dir))
        
        (cu/start-daemon!
         {:logfile logfile
          :pidfile pidfile
          :chdir dir}
        binary
        :--log-output           :stderr
        :--name                 (name node)
        :--listen-peer-urls     (peer-url node)
        :--listen-client-urls   (client-url node)
        :--advertise-client-urls        (client-url node)
        :--initial-cluster-state        :new
        :--initial-advertise-peer-urls  (peer-url node)
        :--initial-luster       (initial-cluster test))
      (Thread/sleep 10000)))


    (teardown! [_ test node]
      (info node "tearing down etcd")
      (cu/stop-daemon!  binary pidfile)
      (c/su (c/exec :rm :-rf dir)))

    db/LogFiles
    (log-files [_ test node]
      [logfile])
))


(defrecord Client [conn]
  client/Client
  (open! [this test node]
    (assoc this :conn (v/connect (client-url node)
                                 {:timeout 5000})))

  (setup! [this test])

  (invoke! [_ test op])

  (teardown! [this test])

  (close! [_ test]
    ; If our connection were stateful, we'd close it here. Verschlimmmbesserung
    ; doesn't actually hold connections, so there's nothing to close.
    ))



(defn r   [_ _] {:type :invoke, :f :read, :value nil})
(defn w   [_ _] {:type :invoke, :f :write, :value (rand-int 5)})
(defn cas [_ _] {:type :invoke, :f :cas, :value [(rand-int 5) (rand-int 5)]})



(defn etcd-test
  "Given an options map from the command line runner (e.g. :nodes, :ssh,
  :concurrency, ...), constructs a test map."
  [opts]
  (merge tests/noop-test
         opts
         {:name "etcd"
          :os   debian/os
          :db   (db "v3.1.5")
          :client (Client. nil)
          :generator (->> r
                          (gen/stagger 1)
                          (gen/nemesis nil)
                          (gen/time-limit 15))}))




(defn -main
  "Handles command line arguments. Can either run a test, or a web server for
  browsing results."
  [& args]
  (cli/run! (merge(cli/single-test-cmd {:test-fn etcd-test})
                  (cli/serve-cmd))
            args))



```

Can you help me @aphyr

**Comment by aphyr** [comment]
On 07/12/2018 05:50 AM, fengchuimailang wrote:
> when I learn jepsen by following the tutorial 3.Writing a Client an error 
> occurred。 but I don‘t how to fix it。

This is covered by the very next line of the tutorial:

 > This throws a bunch of errors, because we haven't told the client how to
 > interpret these reads yet...

--Kyle

**Comment by fengchuimailang** [comment]
Sorry for my carelessness. I didn't see That.
