### ISSUE TITLE
 Process indeterminate ?

### ISSUE THREAD

**Issue by demiaowu** [jepsen-io/jepsen#284]
alaway  Process indeterminate ?
> WARN  jepsen.core - Process 21 indeterminate
java.lang.RuntimeException: 

	at jepsen.control$throw_on_nonzero_exit.invokeStatic(control.clj:105)
	at jepsen.control$throw_on_nonzero_exit.invoke(control.clj:100)
	at jepsen.control$exec_STAR_.invokeStatic(control.clj:120)
	at jepsen.control$exec_STAR_.doInvoke(control.clj:117)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$apply.invoke(core.clj:641)
	at jepsen.control$exec.invokeStatic(control.clj:136)
	at jepsen.control$exec.doInvoke(control.clj:130)
	at clojure.lang.RestFn.invoke(RestFn.java:930)
	at jepsen.atomic$atomic_cas_BANG_.invokeStatic(atomic.clj:123)
	at jepsen.atomic$atomic_cas_BANG_.invoke(atomic.clj:116)
	at jepsen.atomic.CASClient.invoke_BANG_(atomic.clj:155)
	at jepsen.core$worker$fn__8595$fn__8596.invoke(core.clj:138)
	at jepsen.core$worker$fn__8595.invoke(core.clj:136)
	at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:
1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java
:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by daipeixian** [comment]
> alaway Process indeterminate ?
> 
> > WARN  jepsen.core - Process 21 indeterminate
> > java.lang.RuntimeException:
> 
> ```
> at jepsen.control$throw_on_nonzero_exit.invokeStatic(control.clj:105)
> at jepsen.control$throw_on_nonzero_exit.invoke(control.clj:100)
> at jepsen.control$exec_STAR_.invokeStatic(control.clj:120)
> at jepsen.control$exec_STAR_.doInvoke(control.clj:117)
> at clojure.lang.RestFn.applyTo(RestFn.java:137)
> at clojure.core$apply.invokeStatic(core.clj:646)
> at clojure.core$apply.invoke(core.clj:641)
> at jepsen.control$exec.invokeStatic(control.clj:136)
> at jepsen.control$exec.doInvoke(control.clj:130)
> at clojure.lang.RestFn.invoke(RestFn.java:930)
> at jepsen.atomic$atomic_cas_BANG_.invokeStatic(atomic.clj:123)
> at jepsen.atomic$atomic_cas_BANG_.invoke(atomic.clj:116)
> at jepsen.atomic.CASClient.invoke_BANG_(atomic.clj:155)
> at jepsen.core$worker$fn__8595$fn__8596.invoke(core.clj:138)
> at jepsen.core$worker$fn__8595.invoke(core.clj:136)
> at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938)
> at clojure.lang.AFn.call(AFn.java:18)
> at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:
> ```
> 
> 
> ```
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java
> ```
> 
> :624)
> at java.lang.Thread.run(Thread.java:748)

所以兄弟 这个东西的解决方案是什么呢

**Comment by aphyr** [comment]
I don't speak Chinese I'm afraid, and without source or context there's not really much I can say about this error. `jepsen.control$throw_on_nonzero_exit.invokeStatic(control.clj:105)` suggests that some command returned a nonzero exit status, which *should* have come with detailed debugging info about the command, context, exit code, stderr, and stdout, but it doesn't look like they copied that part.

**Comment by daipeixian** [comment]
thanks for your answer, i have found the reason and i am finding the way to solve it




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jepsen-io/jepsen"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月15日(星期四) 晚上9:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jepsen-io/jepsen]  Process indeterminate ? (#284)





 
I don't speak Chinese I'm afraid, and without source or context there's not really much I can say about this error. jepsen.control$throw_on_nonzero_exit.invokeStatic(control.clj:105) suggests that some command returned a nonzero exit status, which should have come with detailed debugging info about the command, context, exit code, stderr, and stdout, but it doesn't look like they copied that part.
