### ISSUE TITLE
java.util.concurrent.BrokenBarrierException: null

### ISSUE THREAD

**Issue by brk0v** [jepsen-io/jepsen#286]
Hello!

I'm trying to reuse nemesis code from _tidb_ and _cocroachdb_ tests and stuck with following errors. Would appreciate any help with it. 

Running inside docker containers, if it matters.

```
WARN [2018-08-13 17:08:11,684] jepsen nemesis - jepsen.core Error running nemesis
java.util.concurrent.BrokenBarrierException: null
        at java.util.concurrent.CyclicBarrier.dowait(CyclicBarrier.java:250) ~[na:1.8.0_171]
        at java.util.concurrent.CyclicBarrier.await(CyclicBarrier.java:362) ~[na:1.8.0_171]
        at jepsen.generator.Synchronize.op(generator.clj:664) ~[jepsen-0.1.10.jar:na]
        at jepsen.generator.Concat.op(generator.clj:606) ~[jepsen-0.1.10.jar:na]
        at jepsen.generator$op_and_validate.invokeStatic(generator.clj:34) ~[jepsen-0.1.10.jar:na]
        at jepsen.generator$op_and_validate.invoke(generator.clj:30) ~[jepsen-0.1.10.jar:na]
        at jepsen.core.NemesisWorker.run_worker_BANG_(core.clj:454) ~[jepsen-0.1.10.jar:na]
        at jepsen.core$do_worker_BANG_.invokeStatic(core.clj:187) [jepsen-0.1.10.jar:na]
        at jepsen.core$do_worker_BANG_.invoke(core.clj:171) [jepsen-0.1.10.jar:na]
        at jepsen.core$run_workers_BANG_$fn__4598$fn__4599.invoke(core.clj:240) [jepsen-0.1.10.jar:na]
        at clojure.lang.AFn.applyToHelper(AFn.java:152) [clojure-1.9.0.jar:na]
        at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.9.0.jar:na]
        at clojure.core$apply.invokeStatic(core.clj:657) [clojure-1.9.0.jar:na]
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1965) [clojure-1.9.0.jar:na]
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1965) [clojure-1.9.0.jar:na]
        at clojure.lang.RestFn.invoke(RestFn.java:425) [clojure-1.9.0.jar:na]
        at clojure.lang.AFn.applyToHelper(AFn.java:156) [clojure-1.9.0.jar:na]
        at clojure.lang.RestFn.applyTo(RestFn.java:132) [clojure-1.9.0.jar:na]
        at clojure.core$apply.invokeStatic(core.clj:661) [clojure-1.9.0.jar:na]
        at clojure.core$bound_fn_STAR_$fn__5471.doInvoke(core.clj:1995) [clojure-1.9.0.jar:na]
        at clojure.lang.RestFn.invoke(RestFn.java:397) [clojure-1.9.0.jar:na]
        at clojure.lang.AFn.run(AFn.java:22) [clojure-1.9.0.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
```

**Comment by aphyr** [comment]
This miiight be caused by error recovery code in Jepsen which is trying to help you escape a deadlock caused by some exceptional condition in the generator itself, but it might also be a race condition *in* that error recovery code. I've taken several stabs at this but haven't managed to come up with a cleanly reproducible test case or a robust error recovery strategy. You're welcome to take a shot at it!

**Comment by aphyr** [comment]
This might fiiiiinally be fixed in 0.1.19 with the introduction of pure generators. It'll take some changes to the test suite though; see jepsen.generator.pure's namespace docs for details.
