### ISSUE TITLE
wrong use of  (net/heal! (:net test) test))) in os setup

### ISSUE THREAD

**Issue by introom** [jepsen-io/jepsen#332]
The heal! function, by default from net/iptables, works on *all* nodes.

Hence, the iptables -F stuff will be repetitively called N times on a single node where N is #nodes.

**Comment by introom** [comment]
besides, constantly see the following error:


WARN [2019-03-05 09:15:32,495] jepsen node p13 - jepsen.control Encountered error with conn [:control "p13"]; reopening

FOLLOWED BY THE TRACE:

ERROR [2019-03-05 09:15:37,214] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
java.util.concurrent.ExecutionException: com.jcraft.jsch.JSchException: channel is not opened.
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_181]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_181]
        at clojure.core$deref_future.invokeStatic(core.clj:2300) ~[clojure-1.10.0.jar:na]
        at clojure.core$future_call$reify__8439.deref(core.clj:6974) ~[clojure-1.10.0.jar:na]
        at clojure.core$deref.invokeStatic(core.clj:2320) ~[clojure-1.10.0.jar:na]
        at clojure.core$deref.invoke(core.clj:2306) ~[clojure-1.10.0.jar:na]
        at clojure.core$map$fn__5851.invoke(core.clj:2753) ~[clojure-1.10.0.jar:na]
        at clojure.lang.LazySeq.sval(LazySeq.java:42) ~[clojure-1.10.0.jar:na]
        at clojure.lang.LazySeq.seq(LazySeq.java:51) ~[clojure-1.10.0.jar:na]
        at clojure.lang.RT.seq(RT.java:531) ~[clojure-1.10.0.jar:na]
        at clojure.core$seq__5387.invokeStatic(core.clj:137) ~[clojure-1.10.0.jar:na]
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24) ~[clojure-1.10.0.jar:na]
        at clojure.core.protocols$fn__8131.invokeStatic(protocols.clj:75) ~[clojure-1.10.0.jar:na]
        at clojure.core.protocols$fn__8131.invoke(protocols.clj:75) ~[clojure-1.10.0.jar:na]
        at clojure.core.protocols$fn__8073$G__8068__8086.invoke(protocols.clj:13) ~[clojure-1.10.0.jar:na]
        at clojure.core$reduce.invokeStatic(core.clj:6828) ~[clojure-1.10.0.jar:na]
        at clojure.core$into.invokeStatic(core.clj:6895) ~[clojure-1.10.0.jar:na]
        at clojure.core$into.invoke(core.clj:6887) ~[clojure-1.10.0.jar:na]


I bet there is something limiting the concurrent ssh connections, either from the sshd side, e.g., MaxSessions configuration (more likely),  or from the jsch side.  But I haven't investigated much.

This might be denoted in somewhere in the doc.

**Comment by aphyr** [comment]
I haven't seen this one before, but I'm nut surprised; JSch has been notoriously fragile. :-(

**Comment by LintianShi** [comment]
Can it be solved? I think I have met this problem too

**Comment by aphyr** [comment]
You might try the other SSH remotes--try replacing the test's ssh remote with `(jepsen.control.sshj/remote)`.
