### ISSUE TITLE
Execute Jepsen Test on localhost without providing username and password

### ISSUE THREAD

**Issue by same3r** [jepsen-io/jepsen#412]
Hi,

I need help with a Jepsen Test that runs solely on my localhost. Following is how I am launching the test:

```
lein run test --node 127.0.0.1 --username $JEPSEN_USERNAME --password $JEPSEN_PWD -- --time-limit 10 --concurrency 40 --ops-per-key 20 -r 1/5 --threads-per-key 10 
```

However, I would like to run the test using a private key without providing username and password.
```
lein run test --node 127.0.0.1 --ssh-private-key ~/.ssh/id_rsa --time-limit 10 --concurrency 40 --ops-per-key 20 -r 1/5 --threads-per-key 10 
```

I have configured my localhost for passwordless ssh. However, when I run the above command the test fails with following exception.
```
WARN [2019-09-10 18:34:03,274] main - jepsen.core Test crashed!
clojure.lang.ExceptionInfo: throw+: {:dir "/", :private-key-path "/Users/sameerch/.ssh/id_rsa", :password "root", :username "root", :type :jepsen.control/session-error, :port 22, :strict-host-key-checking false, :host nil, :sudo nil, :dummy nil, :message "Error opening SSH session. Verify username, password, and node hostnames are correct.", :session nil}
	at slingshot.support$stack_trace.invoke(support.clj:201) ~[knossos-0.3.4.jar:na]
	at jepsen.control$session$fn__2909.invoke(control.clj:318) ~[jepsen-0.1.15.jar:na]
	at jepsen.reconnect$open_BANG_$fn__2781.invoke(reconnect.clj:59) ~[jepsen-0.1.15.jar:na]
	at jepsen.reconnect$open_BANG_.invokeStatic(reconnect.clj:57) ~[jepsen-0.1.15.jar:na]
	at jepsen.reconnect$open_BANG_.invoke(reconnect.clj:54) ~[jepsen-0.1.15.jar:na]
	at jepsen.control$session.invokeStatic(control.clj:312) ~[jepsen-0.1.15.jar:na]
	at jepsen.control$session.invoke(control.clj:309) ~[jepsen-0.1.15.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[clojure-1.10.0.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.10.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:665) ~[clojure-1.10.0.jar:na]
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973) ~[clojure-1.10.0.jar:na]
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973) ~[clojure-1.10.0.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:142) ~[clojure-1.10.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:669) ~[clojure-1.10.0.jar:na]
	at clojure.core$bound_fn_STAR_$fn__5734.doInvoke(core.clj:2003) ~[clojure-1.10.0.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) ~[clojure-1.10.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:665) ~[clojure-1.10.0.jar:na]
	at clojure.core$apply.invoke(core.clj:660) ~[clojure-1.10.0.jar:na]
	at jepsen.util$fcatch$wrapper__2044.doInvoke(util.clj:37) ~[jepsen-0.1.15.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.10.0.jar:na]
	at dom_top.core$real_pmap_helper$build_thread__214$fn__215.invoke(core.clj:146) ~[jepsen-0.1.15.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:152) ~[clojure-1.10.0.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.10.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:665) ~[clojure-1.10.0.jar:na]
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973) ~[clojure-1.10.0.jar:na]
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973) ~[clojure-1.10.0.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:425) ~[clojure-1.10.0.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:156) ~[clojure-1.10.0.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:132) ~[clojure-1.10.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:669) ~[clojure-1.10.0.jar:na]
	at clojure.core$bound_fn_STAR_$fn__5734.doInvoke(core.clj:2003) ~[clojure-1.10.0.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:397) ~[clojure-1.10.0.jar:na]
	at clojure.lang.AFn.run(AFn.java:22) ~[clojure-1.10.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_202]
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:512) ~[jsch-0.1.53.jar:na]
	at com.jcraft.jsch.Session.connect(Session.java:183) ~[jsch-0.1.53.jar:na]
	at clj_ssh.ssh$fn__2477.invokeStatic(ssh.clj:118) ~[jepsen-0.1.15.jar:na]
	at clj_ssh.ssh$fn__2477.invoke(ssh.clj:115) ~[jepsen-0.1.15.jar:na]
	at clj_ssh.ssh.protocols$fn__2435$G__2402__2444.invoke(protocols.clj:4) ~[jepsen-0.1.15.jar:na]
	at clj_ssh.ssh$connect.invokeStatic(ssh.clj:401) ~[jepsen-0.1.15.jar:na]
	at clj_ssh.ssh$connect.invoke(ssh.clj:397) ~[jepsen-0.1.15.jar:na]
	at jepsen.control$clj_ssh_session.invokeStatic(control.clj:307) ~[jepsen-0.1.15.jar:na]
	at jepsen.control$clj_ssh_session.invoke(control.clj:293) ~[jepsen-0.1.15.jar:na]
	at jepsen.control$session$fn__2909.invoke(control.clj:316) ~[jepsen-0.1.15.jar:na]
	... 32 common frames omitted
ERROR [2019-09-10 18:34:03,282] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
clojure.lang.ExceptionInfo: throw+: {:dir "/", :private-key-path "/Users/sameerch/.ssh/id_rsa", :password "root", :username "root", :type :jepsen.control/session-error, :port 22, :strict-host-key-checking false, :host nil, :sudo nil, :dummy nil, :message "Error opening SSH session. Verify username, password, and node hostnames are correct.", :session nil}
	at slingshot.support$stack_trace.invoke(support.clj:201) ~[knossos-0.3.4.jar:na]
	at jepsen.control$session$fn__2909.invoke(control.clj:318) ~[jepsen-0.1.15.jar:na]
	at jepsen.reconnect$open_BANG_$fn__2781.invoke(reconnect.clj:59) ~[jepsen-0.1.15.jar:na]
	at jepsen.reconnect$open_BANG_.invokeStatic(reconnect.clj:57) ~[jepsen-0.1.15.jar:na]
	at jepsen.reconnect$open_BANG_.invoke(reconnect.clj:54) ~[jepsen-0.1.15.jar:na]
	at jepsen.control$session.invokeStatic(control.clj:312) ~[jepsen-0.1.15.jar:na]
	at jepsen.control$session.invoke(control.clj:309) ~[jepsen-0.1.15.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[clojure-1.10.0.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.10.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:665) ~[clojure-1.10.0.jar:na]
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973) ~[clojure-1.10.0.jar:na]
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973) ~[clojure-1.10.0.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:142) ~[clojure-1.10.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:669) ~[clojure-1.10.0.jar:na]
	at clojure.core$bound_fn_STAR_$fn__5734.doInvoke(core.clj:2003) ~[clojure-1.10.0.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) ~[clojure-1.10.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:665) ~[clojure-1.10.0.jar:na]
	at clojure.core$apply.invoke(core.clj:660) ~[clojure-1.10.0.jar:na]
	at jepsen.util$fcatch$wrapper__2044.doInvoke(util.clj:37) ~[jepsen-0.1.15.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.10.0.jar:na]
	at dom_top.core$real_pmap_helper$build_thread__214$fn__215.invoke(core.clj:146) ~[jepsen-0.1.15.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:152) ~[clojure-1.10.0.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.10.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:665) ~[clojure-1.10.0.jar:na]
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973) ~[clojure-1.10.0.jar:na]
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973) ~[clojure-1.10.0.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:425) ~[clojure-1.10.0.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:156) ~[clojure-1.10.0.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:132) ~[clojure-1.10.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:669) ~[clojure-1.10.0.jar:na]
	at clojure.core$bound_fn_STAR_$fn__5734.doInvoke(core.clj:2003) ~[clojure-1.10.0.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:397) ~[clojure-1.10.0.jar:na]
	at clojure.lang.AFn.run(AFn.java:22) ~[clojure-1.10.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_202]
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:512) ~[jsch-0.1.53.jar:na]
	at com.jcraft.jsch.Session.connect(Session.java:183) ~[jsch-0.1.53.jar:na]
	at clj_ssh.ssh$fn__2477.invokeStatic(ssh.clj:118) ~[jepsen-0.1.15.jar:na]
	at clj_ssh.ssh$fn__2477.invoke(ssh.clj:115) ~[jepsen-0.1.15.jar:na]
	at clj_ssh.ssh.protocols$fn__2435$G__2402__2444.invoke(protocols.clj:4) ~[jepsen-0.1.15.jar:na]
	at clj_ssh.ssh$connect.invokeStatic(ssh.clj:401) ~[jepsen-0.1.15.jar:na]
	at clj_ssh.ssh$connect.invoke(ssh.clj:397) ~[jepsen-0.1.15.jar:na]
	at jepsen.control$clj_ssh_session.invokeStatic(control.clj:307) ~[jepsen-0.1.15.jar:na]
	at jepsen.control$clj_ssh_session.invoke(control.clj:293) ~[jepsen-0.1.15.jar:na]
	at jepsen.control$session$fn__2909.invoke(control.clj:316) ~[jepsen-0.1.15.jar:na]
	... 32 common frames omitted
```

Requesting pointers to debug and fix the issue.

**Comment by same3r** [comment]
I was able to get ssh less test to work for localhost.  `jepsen.control/with-ssh` accepts `:dummy?` arg. Just had to add the arg to the ssh map of the test definition.

Here, is an example where @aphyr used it.
