### ISSUE TITLE
Error in analysis

### ISSUE THREAD

**Issue by wfystx** [jepsen-io/jepsen#431]
`2020-01-02 20:00:16,996{GMT}    WARN    [clojure-agent-send-off-pool-2] jepsen.checker: Error while checking history:
java.lang.IllegalStateException: Error rendering plot, verify gnuplot is installed and reachable
        at jepsen.checker.perf$plot_BANG_.invokeStatic(perf.clj:478) ~[jepsen-0.1.15-SNAPSHOT.jar:na]
        at jepsen.checker.perf$plot_BANG_.invoke(perf.clj:415) ~[jepsen-0.1.15-SNAPSHOT.jar:na]
        at jepsen.checker.perf$rate_graph_BANG_.invokeStatic(perf.clj:591) ~[jepsen-0.1.15-SNAPSHOT.jar:na]
        at jepsen.checker.perf$rate_graph_BANG_.invoke(perf.clj:556) ~[jepsen-0.1.15-SNAPSHOT.jar:na]
        at jepsen.checker$rate_graph$reify__4944.check(checker.clj:758) ~[jepsen-0.1.15-SNAPSHOT.jar:na]
        at jepsen.checker$check_safe.invokeStatic(checker.clj:84) [jepsen-0.1.15-SNAPSHOT.jar:na]
        at jepsen.checker$check_safe.invoke(checker.clj:77) [jepsen-0.1.15-SNAPSHOT.jar:na]
        at jepsen.checker$compose$reify__4747$fn__4749.invoke(checker.clj:100) [jepsen-0.1.15-SNAPSHOT.jar:na]
        at clojure.core$pmap$fn__8447$fn__8448.invoke(core.clj:7022) [clojure-1.10.0.jar:na]
        at clojure.core$binding_conveyor_fn$fn__5739.invoke(core.clj:2030) [clojure-1.10.0.jar:na]
        at clojure.lang.AFn.call(AFn.java:18) [clojure-1.10.0.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222]`

I meet this problem almost 3/4 times of my tests, can't get the result. 
`Errors occurred during analysis, but no anomalies found. ಠ~ಠ`

**Comment by vjuranek** [comment]
and have you `verify gnuplot is installed and reachable` ?

**Comment by aphyr** [comment]
This might also be easier to debug in Jepsen 0.1.16, which includes gnuplot error messages in this exception. :)On Jan 3, 2020 04:39, Vojtěch Juránek <notifications@github.com> wrote:and have you verify gnuplot is installed and reachable ?

**Comment by wfystx** [comment]
> and have you `verify gnuplot is installed and reachable` ?

Yes I have verified gnuplot is installed and reachable.
This error doesn't occur every time I run. The diagram can be successfully made some times.

**Comment by wfystx** [comment]
When I run a test for a long time period like 5 hours, this error occurs.

**Comment by aphyr** [comment]
This miiight be resolved in the upcoming release of Jepsen; I've made improvements to gnuplot for long-running tests with tons of nemesis operations.
