### ISSUE TITLE
checker/linearisable {:algorithm :wgl} causes error to be thrown during analysis

### ISSUE THREAD

**Issue by stevana** [jepsen-io/jepsen#439]
When I change the algorithm to `:wgl` in:

```clojure
(checker/linearizable
    {:model     (model)
    :algorithm :linear})}
```

I see the following error:

```
INFO [2020-02-19 12:38:00,342] jepsen test runner - jepsen.core Analyzing...
INFO [2020-02-19 12:38:05,352] knossos reporter - knossos.search [:WGL]
INFO [2020-02-19 12:38:09,671] Thread-281 - knossos.model.memo More than 1024 reachable models; not memoizing models for this search
WARN [2020-02-19 12:13:44,176] jepsen test runner - jepsen.checker Error while checking history:
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: Method knossos/wgl/Op.iterator()Ljava/util/Iterator;
 is abstract
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_222]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_222]
        at clojure.core$deref_future.invokeStatic(core.clj:2300) ~[clojure-1.10.1.jar:na]
        at clojure.core$future_call$reify__8454.deref(core.clj:6974) ~[clojure-1.10.1.jar:na]
        at clojure.core$deref.invokeStatic(core.clj:2320) ~[clojure-1.10.1.jar:na]
        at clojure.core$deref.invoke(core.clj:2306) ~[clojure-1.10.1.jar:na]
        at clojure.core$map$fn__5866.invoke(core.clj:2755) ~[clojure-1.10.1.jar:na]
        at clojure.lang.LazySeq.sval(LazySeq.java:42) ~[clojure-1.10.1.jar:na]
        at clojure.lang.LazySeq.seq(LazySeq.java:51) ~[clojure-1.10.1.jar:na]
        at clojure.lang.Cons.next(Cons.java:39) ~[clojure-1.10.1.jar:na]
        at clojure.lang.RT.next(RT.java:713) ~[clojure-1.10.1.jar:na]
        at clojure.core$next__5386.invokeStatic(core.clj:64) ~[clojure-1.10.1.jar:na]
        at clojure.core.protocols$fn__8159.invokeStatic(protocols.clj:169) ~[clojure-1.10.1.jar:na]
        at clojure.core.protocols$fn__8159.invoke(protocols.clj:124) ~[clojure-1.10.1.jar:na]
        at clojure.core.protocols$fn__8114$G__8109__8123.invoke(protocols.clj:19) ~[clojure-1.10.1.jar:na]
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31) ~[clojure-1.10.1.jar:na]
        at clojure.core.protocols$fn__8146.invokeStatic(protocols.clj:75) ~[clojure-1.10.1.jar:na]
        at clojure.core.protocols$fn__8146.invoke(protocols.clj:75) ~[clojure-1.10.1.jar:na]
        at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13) ~[clojure-1.10.1.jar:na]
        at clojure.core$reduce.invokeStatic(core.clj:6828) ~[clojure-1.10.1.jar:na]
        at clojure.core$into.invokeStatic(core.clj:6895) ~[clojure-1.10.1.jar:na]
        at clojure.core$into.invoke(core.clj:6887) ~[clojure-1.10.1.jar:na]
        at jepsen.checker$compose$reify__4964.check(checker.clj:101) ~[jepsen-0.1.17.jar:na]
        at jepsen.checker$check_safe.invokeStatic(checker.clj:84) [jepsen-0.1.17.jar:na]
        at jepsen.checker$check_safe.invoke(checker.clj:77) [jepsen-0.1.17.jar:na]
        at jepsen.checker$check_safe.invokeStatic(checker.clj:82) [jepsen-0.1.17.jar:na]
        at jepsen.checker$check_safe.invoke(checker.clj:77) [jepsen-0.1.17.jar:na]
        at jepsen.core$analyze_BANG_.invokeStatic(core.clj:463) [jepsen-0.1.17.jar:na]
        at jepsen.core$analyze_BANG_.invoke(core.clj:452) [jepsen-0.1.17.jar:na]
        at jepsen.core$run_BANG_$fn__5840$fn__5847.invoke(core.clj:586) [jepsen-0.1.17.jar:na]
        at jepsen.core$run_BANG_$fn__5840.invoke(core.clj:573) [jepsen-0.1.17.jar:na]
        at jepsen.core$run_BANG_.invokeStatic(core.clj:559) [jepsen-0.1.17.jar:na]
        at jepsen.core$run_BANG_.invoke(core.clj:486) [jepsen-0.1.17.jar:na]
        at jepsen.cli$single_test_cmd$fn__6590.invoke(cli.clj:369) [jepsen-0.1.17.jar:na]
        at jepsen.cli$run_BANG_.invokeStatic(cli.clj:306) [jepsen-0.1.17.jar:na]
        at jepsen.cli$run_BANG_.invoke(cli.clj:236) [jepsen-0.1.17.jar:na]
        at main$_main.invokeStatic(main.clj:215) [na:na]
        at main$_main.doInvoke(main.clj:212) [na:na]
        at clojure.lang.RestFn.invoke(RestFn.java:703) [clojure-1.10.1.jar:na]
        at clojure.lang.Var.invoke(Var.java:447) [clojure-1.10.1.jar:na]
        at user$eval140.invokeStatic(form-init1779096441796326842.clj:1) [na:na]
        at user$eval140.invoke(form-init1779096441796326842.clj:1) [na:na]
        at clojure.lang.Compiler.eval(Compiler.java:7177) [clojure-1.10.1.jar:na]
        at clojure.lang.Compiler.eval(Compiler.java:7167) [clojure-1.10.1.jar:na]
        at clojure.lang.Compiler.load(Compiler.java:7636) [clojure-1.10.1.jar:na]
        at clojure.lang.Compiler.loadFile(Compiler.java:7574) [clojure-1.10.1.jar:na]
        at clojure.main$load_script.invokeStatic(main.clj:475) [clojure-1.10.1.jar:na]
        at clojure.main$init_opt.invokeStatic(main.clj:477) [clojure-1.10.1.jar:na]
        at clojure.main$init_opt.invoke(main.clj:477) [clojure-1.10.1.jar:na]
        at clojure.main$initialize.invokeStatic(main.clj:508) [clojure-1.10.1.jar:na]
        at clojure.main$null_opt.invokeStatic(main.clj:542) [clojure-1.10.1.jar:na]
        at clojure.main$null_opt.invoke(main.clj:539) [clojure-1.10.1.jar:na]
        at clojure.main$main.invokeStatic(main.clj:664) [clojure-1.10.1.jar:na]
        at clojure.main$main.doInvoke(main.clj:616) [clojure-1.10.1.jar:na]
        at clojure.lang.RestFn.applyTo(RestFn.java:137) [clojure-1.10.1.jar:na]
        at clojure.lang.Var.applyTo(Var.java:705) [clojure-1.10.1.jar:na]
        at clojure.main.main(main.java:40) [clojure-1.10.1.jar:na]
Caused by: java.lang.AbstractMethodError: Method knossos/wgl/Op.iterator()Ljava/util/Iterator; is abstract
        at knossos.wgl.Op.iterator(wgl.clj) ~[knossos-0.3.6.jar:na]
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:46) ~[clojure-1.10.1.jar:na]
        at clojure.core.protocols$fn__8140.invokeStatic(protocols.clj:75) ~[clojure-1.10.1.jar:na]
        at clojure.core.protocols$fn__8140.invoke(protocols.clj:75) ~[clojure-1.10.1.jar:na]
        at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13) ~[clojure-1.10.1.jar:na]
        at clojure.core$reduce.invokeStatic(core.clj:6828) ~[clojure-1.10.1.jar:na]
        at clojure.core$into.invokeStatic(core.clj:6895) ~[clojure-1.10.1.jar:na]
        at clojure.core$into.invoke(core.clj:6887) ~[clojure-1.10.1.jar:na]
        at knossos.op$Op__GT_map.invokeStatic(op.clj:14) ~[knossos-0.3.6.jar:na]
        at knossos.op$Op__GT_map.invoke(op.clj:11) ~[knossos-0.3.6.jar:na]
        at model$mismatch$fn__14928.invoke(model.clj:151) ~[na:na]
        at model$mismatch.invokeStatic(model.clj:150) ~[na:na]
        at model$mismatch.invoke(model.clj:147) ~[na:na]
        at model.Model.step(model.clj:182) ~[na:na]
        at knossos.wgl$check.invokeStatic(wgl.clj:522) ~[knossos-0.3.6.jar:na]
        at knossos.wgl$check.invoke(wgl.clj:488) ~[knossos-0.3.6.jar:na]
        at knossos.wgl$start_analysis$fn__3504.invoke(wgl.clj:595) ~[knossos-0.3.6.jar:na]
        at clojure.lang.AFn.run(AFn.java:22) ~[clojure-1.10.1.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_222]
INFO [2020-02-19 12:13:44,179] jepsen test runner - jepsen.core Analysis complete
```

**Comment by aphyr** [comment]
Sounds like this could be a knossos bug? Might be worth trying to repro in the knossos test suite directly...On Feb 19, 2020 07:53, Stevan Andjelkovic <notifications@github.com> wrote:When I change the algorithm to :wgl in:
(checker/linearizable
    {:model     (model)
    :algorithm :linear})}
I see the following error:
INFO [2020-02-19 12:38:00,342] jepsen test runner - jepsen.core Analyzing...
INFO [2020-02-19 12:38:05,352] knossos reporter - knossos.search [:WGL]
INFO [2020-02-19 12:38:09,671] Thread-281 - knossos.model.memo More than 1024 reachable models; not memoizing models for this search
WARN [2020-02-19 12:13:44,176] jepsen test runner - jepsen.checker Error while checking history:
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: Method knossos/wgl/Op.iterator()Ljava/util/Iterator;
 is abstract
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_222]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_222]
        at clojure.core$deref_future.invokeStatic(core.clj:2300) ~[clojure-1.10.1.jar:na]
        at clojure.core$future_call$reify__8454.deref(core.clj:6974) ~[clojure-1.10.1.jar:na]
        at clojure.core$deref.invokeStatic(core.clj:2320) ~[clojure-1.10.1.jar:na]
        at clojure.core$deref.invoke(core.clj:2306) ~[clojure-1.10.1.jar:na]
        at clojure.core$map$fn__5866.invoke(core.clj:2755) ~[clojure-1.10.1.jar:na]
        at clojure.lang.LazySeq.sval(LazySeq.java:42) ~[clojure-1.10.1.jar:na]
        at clojure.lang.LazySeq.seq(LazySeq.java:51) ~[clojure-1.10.1.jar:na]
        at clojure.lang.Cons.next(Cons.java:39) ~[clojure-1.10.1.jar:na]
        at clojure.lang.RT.next(RT.java:713) ~[clojure-1.10.1.jar:na]
        at clojure.core$next__5386.invokeStatic(core.clj:64) ~[clojure-1.10.1.jar:na]
        at clojure.core.protocols$fn__8159.invokeStatic(protocols.clj:169) ~[clojure-1.10.1.jar:na]
        at clojure.core.protocols$fn__8159.invoke(protocols.clj:124) ~[clojure-1.10.1.jar:na]
        at clojure.core.protocols$fn__8114$G__8109__8123.invoke(protocols.clj:19) ~[clojure-1.10.1.jar:na]
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31) ~[clojure-1.10.1.jar:na]
        at clojure.core.protocols$fn__8146.invokeStatic(protocols.clj:75) ~[clojure-1.10.1.jar:na]
        at clojure.core.protocols$fn__8146.invoke(protocols.clj:75) ~[clojure-1.10.1.jar:na]
        at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13) ~[clojure-1.10.1.jar:na]
        at clojure.core$reduce.invokeStatic(core.clj:6828) ~[clojure-1.10.1.jar:na]
        at clojure.core$into.invokeStatic(core.clj:6895) ~[clojure-1.10.1.jar:na]
        at clojure.core$into.invoke(core.clj:6887) ~[clojure-1.10.1.jar:na]
        at jepsen.checker$compose$reify__4964.check(checker.clj:101) ~[jepsen-0.1.17.jar:na]
        at jepsen.checker$check_safe.invokeStatic(checker.clj:84) [jepsen-0.1.17.jar:na]
        at jepsen.checker$check_safe.invoke(checker.clj:77) [jepsen-0.1.17.jar:na]
        at jepsen.checker$check_safe.invokeStatic(checker.clj:82) [jepsen-0.1.17.jar:na]
        at jepsen.checker$check_safe.invoke(checker.clj:77) [jepsen-0.1.17.jar:na]
        at jepsen.core$analyze_BANG_.invokeStatic(core.clj:463) [jepsen-0.1.17.jar:na]
        at jepsen.core$analyze_BANG_.invoke(core.clj:452) [jepsen-0.1.17.jar:na]
        at jepsen.core$run_BANG_$fn__5840$fn__5847.invoke(core.clj:586) [jepsen-0.1.17.jar:na]
        at jepsen.core$run_BANG_$fn__5840.invoke(core.clj:573) [jepsen-0.1.17.jar:na]
        at jepsen.core$run_BANG_.invokeStatic(core.clj:559) [jepsen-0.1.17.jar:na]
        at jepsen.core$run_BANG_.invoke(core.clj:486) [jepsen-0.1.17.jar:na]
        at jepsen.cli$single_test_cmd$fn__6590.invoke(cli.clj:369) [jepsen-0.1.17.jar:na]
        at jepsen.cli$run_BANG_.invokeStatic(cli.clj:306) [jepsen-0.1.17.jar:na]
        at jepsen.cli$run_BANG_.invoke(cli.clj:236) [jepsen-0.1.17.jar:na]
        at main$_main.invokeStatic(main.clj:215) [na:na]
        at main$_main.doInvoke(main.clj:212) [na:na]
        at clojure.lang.RestFn.invoke(RestFn.java:703) [clojure-1.10.1.jar:na]
        at clojure.lang.Var.invoke(Var.java:447) [clojure-1.10.1.jar:na]
        at user$eval140.invokeStatic(form-init1779096441796326842.clj:1) [na:na]
        at user$eval140.invoke(form-init1779096441796326842.clj:1) [na:na]
        at clojure.lang.Compiler.eval(Compiler.java:7177) [clojure-1.10.1.jar:na]
        at clojure.lang.Compiler.eval(Compiler.java:7167) [clojure-1.10.1.jar:na]
        at clojure.lang.Compiler.load(Compiler.java:7636) [clojure-1.10.1.jar:na]
        at clojure.lang.Compiler.loadFile(Compiler.java:7574) [clojure-1.10.1.jar:na]
        at clojure.main$load_script.invokeStatic(main.clj:475) [clojure-1.10.1.jar:na]
        at clojure.main$init_opt.invokeStatic(main.clj:477) [clojure-1.10.1.jar:na]
        at clojure.main$init_opt.invoke(main.clj:477) [clojure-1.10.1.jar:na]
        at clojure.main$initialize.invokeStatic(main.clj:508) [clojure-1.10.1.jar:na]
        at clojure.main$null_opt.invokeStatic(main.clj:542) [clojure-1.10.1.jar:na]
        at clojure.main$null_opt.invoke(main.clj:539) [clojure-1.10.1.jar:na]
        at clojure.main$main.invokeStatic(main.clj:664) [clojure-1.10.1.jar:na]
        at clojure.main$main.doInvoke(main.clj:616) [clojure-1.10.1.jar:na]
        at clojure.lang.RestFn.applyTo(RestFn.java:137) [clojure-1.10.1.jar:na]
        at clojure.lang.Var.applyTo(Var.java:705) [clojure-1.10.1.jar:na]
        at clojure.main.main(main.java:40) [clojure-1.10.1.jar:na]
Caused by: java.lang.AbstractMethodError: Method knossos/wgl/Op.iterator()Ljava/util/Iterator; is abstract
        at knossos.wgl.Op.iterator(wgl.clj) ~[knossos-0.3.6.jar:na]
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:46) ~[clojure-1.10.1.jar:na]
        at clojure.core.protocols$fn__8140.invokeStatic(protocols.clj:75) ~[clojure-1.10.1.jar:na]
        at clojure.core.protocols$fn__8140.invoke(protocols.clj:75) ~[clojure-1.10.1.jar:na]
        at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13) ~[clojure-1.10.1.jar:na]
        at clojure.core$reduce.invokeStatic(core.clj:6828) ~[clojure-1.10.1.jar:na]
        at clojure.core$into.invokeStatic(core.clj:6895) ~[clojure-1.10.1.jar:na]
        at clojure.core$into.invoke(core.clj:6887) ~[clojure-1.10.1.jar:na]
        at knossos.op$Op__GT_map.invokeStatic(op.clj:14) ~[knossos-0.3.6.jar:na]
        at knossos.op$Op__GT_map.invoke(op.clj:11) ~[knossos-0.3.6.jar:na]
        at model$mismatch$fn__14928.invoke(model.clj:151) ~[na:na]
        at model$mismatch.invokeStatic(model.clj:150) ~[na:na]
        at model$mismatch.invoke(model.clj:147) ~[na:na]
        at model.Model.step(model.clj:182) ~[na:na]
        at knossos.wgl$check.invokeStatic(wgl.clj:522) ~[knossos-0.3.6.jar:na]
        at knossos.wgl$check.invoke(wgl.clj:488) ~[knossos-0.3.6.jar:na]
        at knossos.wgl$start_analysis$fn__3504.invoke(wgl.clj:595) ~[knossos-0.3.6.jar:na]
        at clojure.lang.AFn.run(AFn.java:22) ~[clojure-1.10.1.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_222]
INFO [2020-02-19 12:13:44,179] jepsen test runner - jepsen.core Analysis complete
