### ISSUE TITLE
noop-test failed on the windowsOS

### ISSUE THREAD

**Issue by codeBabyLin** [jepsen-io/jepsen#488]
It turns out Exceptions while running the noop-test on the windows10. Here is the main error info:

ERROR [2020-09-14 17:24:44,136] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
clojure.lang.ExceptionInfo: throw+: {:dir "/", :private-key-path nil, :password "root", :username "root", :type :jepsen.control/session-error, :port 22, :strict-host-key-checking false, :host nil, :sudo nil, :dummy false, :message "Error opening SSH session. Verify username, password, and node hostnames are correct.", :session nil}
	at slingshot.support$stack_trace.invoke(support.clj:201)
	at jepsen.control.SSHRemote$fn__3121.invoke(control.clj:322)
	at jepsen.control.SSHRemote.connect(control.clj:319)
	at jepsen.control$session$fn__3136.invoke(control.clj:350)
	at jepsen.reconnect$open_BANG_$fn__2910.invoke(reconnect.clj:59)
	at jepsen.reconnect$open_BANG_.invokeStatic(reconnect.clj:57)
	at jepsen.reconnect$open_BANG_.invoke(reconnect.clj:54)
	at jepsen.control$session.invokeStatic(control.clj:349)
	at jepsen.control$session.invoke(control.clj:345)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$bound_fn_STAR_$fn__5734.doInvoke(core.clj:2003)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at jepsen.util$fcatch$wrapper__2167.doInvoke(util.clj:38)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at dom_top.core$real_pmap_helper$build_thread__213$fn__214.invoke(core.clj:146)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$bound_fn_STAR_$fn__5734.doInvoke(core.clj:2003)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.jcraft.jsch.JSchException: java.net.UnknownHostException: n1

**Comment by rkochar** [comment]
What fixed it?

**Comment by rkochar** [comment]
Add `{:ssh {:dummy? true}}` in opts. See [this](https://github.com/jepsen-io/jepsen/blob/ba6adb7915aa8373356a7f11704ea16e56420f59/jepsen/test/jepsen/core_test.clj#L58).
