### ISSUE TITLE
Could not initialize class

### ISSUE THREAD

**Issue by ashwinbhaskar** [jepsen-io/jepsen#548]
I am going through the [tutorial](https://github.com/jepsen-io/jepsen/blob/main/doc/tutorial/01-scaffolding.md) and typing and executing the commands one by one. I get the following error when I run `lein run test`. What am I missing?

```
ERROR [2022-08-10 17:33:59,675] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
java.lang.NoClassDefFoundError: Could not initialize class com.jcraft.jsch.agentproxy.usocket.JNAUSocketFactory$CLibrary
```

**Comment by ashwinbhaskar** [comment]
@eskuai This is my `project.clj`

```
(defproject jepsen.etcdemo "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.10.3"]
                 [jepsen "0.2.1-SNAPSHOT"]
                 [verschlimmbesserung "0.1.3"]]
  :main jepsen.etcdemo
  :repl-options {:init-ns jepsen.etcdemo})
```

I was running this code
```
(ns jepsen.etcdemo
  (:require [jepsen.cli :as cli]
            [jepsen.tests :as tests]))

(defn etcd-test
  [opts]
  (merge tests/noop-test
         {:pure-generators true}
         opts))

(defn -main
  [& args]
  (cli/run! (cli/single-test-cmd {:test-fn etcd-test})
            args))
```

**Comment by aphyr** [comment]
The JNA class not found error suggests to me that this might be related to some kind of broken/missing JNA thing, possibly involving the SSHJ library. Might be something you can work around by switching the :remote in the test to the clj-ssh remote, instead of the sshj remote, but without being able to reproduce the issue I'm not really sure.On Aug 10, 2022 23:33, Ashwin Bhaskar ***@***.***> wrote:
@eskuai This is my project.clj
(defproject jepsen.etcdemo "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.10.3"]
                 [jepsen "0.2.1-SNAPSHOT"]
                 [verschlimmbesserung "0.1.3"]]
  :main jepsen.etcdemo
  :repl-options {:init-ns jepsen.etcdemo})

I was running this code
(ns jepsen.etcdemo
  (:require [jepsen.cli :as cli]
            [jepsen.tests :as tests]))

(defn etcd-test
  [opts]
  (merge tests/noop-test
         {:pure-generators true}
         opts))

(defn -main
  [& args]
  (cli/run! (cli/single-test-cmd {:test-fn etcd-test})
            args))

**Comment by ashwinbhaskar** [comment]
@eskuai tried with `clj-ssh`. still same error. I am running this on Mac with the new M1 chip. Could that be the problem? Is there something I can do to give you more information (more stack traces?) etc?

**Comment by aphyr** [comment]
Ah, yeah, sorry, afraid I don't have a Mac to test with. If it's breaking using both remotes, that suggests that something isn't working when the JVM initially loads classes. Maybe there's some kind of native SSH agent library it expects to bind to that isn't available? I'm afraid JNA's details are outside my realm of expertise--your guess is likely as good as mine here.On Aug 11, 2022 00:11, Ashwin Bhaskar ***@***.***> wrote:
@eskuai tried with clj-ssh. still same error. I am running this on Mac with the new M1 chip. Could that be the problem? Is there something I can do to give you more information (more stack traces?) etc?

**Comment by ashwinbhaskar** [comment]
@eskuai actually my bad. The error is a bit different when running it with `clj-ssh`. This time it is `java.lang.UnsatisfiedLinkError`
```
java.lang.UnsatisfiedLinkError: /private/var/folders/66/8ybncfzx7lzdvsf_twjjg4yh0000gn/T/jna-1232682878/jna13143526714866535945.tmp: dlopen(/private/var/folders/66/8ybncfzx7lzdvsf_twjjg4yh0000gn/T/jna-1232682878/jna13143526714866535945.tmp, 0x0001): tried: '/private/var/folders/66/8ybncfzx7lzdvsf_twjjg4yh0000gn/T/jna-1232682878/jna13143526714866535945.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64,unknown', need 'arm64e'))
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
```

**Comment by ashwinbhaskar** [comment]
@eskuai can I know which JVM version and vendor you are using?

**Comment by eskuai** [comment]
Hi @ashwinbhaskar 

This might be something todo with the JVM/JDK used, 
Have you use jdk11-zulu installed via sdkman ? 
Can you tri installing openjdk11 via brew ?

**Comment by ashwinbhaskar** [comment]
@eskuai I am getting a very strange error with `jdk11-zulu`
```
WARN [2022-08-11 12:23:38,773] nRepl-session-f0d2cd78-f16e-4aeb-8b43-70a1783fefdf - jepsen.core Test crashed!
clojure.lang.ExceptionInfo: throw+: {:dir "/", :private-key-path nil, :password "root", :username "root", :type :jepsen.control/session-error, :port 22, :strict-host-key-checking false, :host nil, :sudo nil, :dummy false, :message "Error opening SSH session. Verify username, password, and node hostnames are correct.", :session nil}
	at slingshot.support$stack_trace.invoke(support.clj:201)
	at jepsen.control.SSHRemote$fn__3132.invoke(control.clj:322)
	at jepsen.control.SSHRemote.connect(control.clj:319)
	at jepsen.control$session$fn__3147.invoke(control.clj:350)
	at jepsen.reconnect$open_BANG_$fn__2921.invoke(reconnect.clj:59)
	at jepsen.reconnect$open_BANG_.invokeStatic(reconnect.clj:57)
	at jepsen.reconnect$open_BANG_.invoke(reconnect.clj:54)
	at jepsen.control$session.invokeStatic(control.clj:349)
	at jepsen.control$session.invoke(control.clj:345)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1977)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1977)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:671)
	at clojure.core$bound_fn_STAR_$fn__5767.doInvoke(core.clj:2007)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at jepsen.util$fcatch$wrapper__2167.doInvoke(util.clj:39)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at dom_top.core$real_pmap_helper$build_thread__213$fn__214.invoke(core.clj:146)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1977)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1977)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:671)
	at clojure.core$bound_fn_STAR_$fn__5767.doInvoke(core.clj:2007)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.jcraft.jsch.JSchException: java.net.UnknownHostException: n1
	at com.jcraft.jsch.Util.createSocket(Util.java:349)
	at com.jcraft.jsch.Session.connect(Session.java:215)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at clj_ssh.ssh$fn__2617.invokeStatic(ssh.clj:118)
	at clj_ssh.ssh$fn__2617.invoke(ssh.clj:115)
	at clj_ssh.ssh.protocols$fn__2575$G__2542__2584.invoke(protocols.clj:4)
	at clj_ssh.ssh$connect.invokeStatic(ssh.clj:401)
	at clj_ssh.ssh$connect.invoke(ssh.clj:397)
	at jepsen.control$clj_ssh_session.invokeStatic(control.clj:311)
	at jepsen.control$clj_ssh_session.invoke(control.clj:298)
	at jepsen.control.SSHRemote$fn__3132.invoke(control.clj:320)
	... 34 common frames omitted
Caused by: java.net.UnknownHostException: n1
```

**Comment by eskuai** [comment]
Hi @ashwinbhaskar 

Now it seems that process starts working ...

This is another configuration issue, 

``` 
Caused by: com.jcraft.jsch.JSchException: java.net.UnknownHostException: n1
	at com.jcraft.jsch.Util.createSocket(Util.java:349)
	at com.jcraft.jsch.Session.connect(Session.java:215)
```

What set up are you using?  docker? lxc ...?

Could you try, getting nodes ips and updating into /etc/hosts ???  check with ping then,

And check more times :
[https://github.com/eskuai/jepsen#faq](url)

**Comment by ashwinbhaskar** [comment]
@eskuai oh okay. I just followed the tutorial. There was no mention of docker. Should I have some docker container running?

**Comment by ashwinbhaskar** [comment]
@eskuai do you have some guide on how to set up test nodes?

**Comment by eskuai** [comment]
Hi @ashwinbhaskar 

have you readed the initial readme?  you should...

I think that the "intro" doc to this project is not "easy" ...  but, make updates and request  to @aphyr for them...

[https://github.com/jepsen-io/jepsen****](url)

and 

[https://github.com/jepsen-io/jepsen#setting-up-a-jepsen-environment ](https://github.com/jepsen-io/jepsen#setting-up-a-jepsen-environment )

I think you're asking for another questions.

Please @ashwinbhaskar,  close this issue and open anothers if you need.

**Comment by rachit77** [comment]
I am getting this same error on mac m1(apple silicone) while trying to run docker compose of tendermint jepsen test suite
