### ISSUE TITLE
error when running jepsen on cockroach db

### ISSUE THREAD

**Issue by rafiw** [jepsen-io/jepsen#575]
Hey,
I'm trying to run Jepsen against a local cluster of 3 cockroach DB servers running on bare metal ubuntu OS.
This is the command I'm running:
`lein run test --test register --nemesis none  -o ubuntu -n n1 -n n2 -n n2 --ssh-private-key  /root/.ssh/id_rsa --username root --tarball https://binaries.cockroachdb.com/cockroach-v22.2.9.linux-amd64.tgz`
I get this error message:
`
ERROR [2023-05-31 23:26:06,676] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
java.util.concurrent.ExecutionException: java.lang.RuntimeException: sudo -S -u cockroach bash -c "cd /opt/cockroach; echo \"{range_min_bytes: 1024, range_max_bytes: 1048576}
\" | /opt/cockroach/cockroach zone set --insecure --file=- .default" returned non-zero exit status 1 on n1. STDOUT:
STDERR:
ERROR: unknown command "zone" for "cockroach"
`

commenting out the zone command [here ](https://github.com/jepsen-io/jepsen/blob/main/cockroachdb/src/jepsen/cockroach.clj#L75)i get:

`
ERROR [2023-05-31 23:59:56,595] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
java.util.concurrent.ExecutionException: java.lang.RuntimeException: sudo -S -u cockroach bash -c "cd /opt/cockroach; /opt/cockroach/cockroach sql --insecure -e \"create database jepsen\" >> /opt/cockroach/logs/cockroach.stderr 2>&1" returned non-zero exit status 1 on n1. STDOUT:
`
what am i missing?
Thanks
full log of the first error

```
{:nemeses [(jepsen.cockroach.nemesis/none)],
 :ssh-private-key "/root/.ssh/id_rsa",
 :concurrency 3,
 :test-fns
 [#object[jepsen.cockroach.register$test 0x1894e40d "jepsen.cockroach.register$test@1894e40d"]],
 :ssh
 {:username "root",
  :password "",
  :strict-host-key-checking false,
  :private-key-path "/root/.ssh/id_rsa"},
 :linearizable false,
 :nemeses2 [nil],
 :nodes ["n1" "n2" "n3"],
 :test-count 1,
 :tarball
 "https://binaries.cockroachdb.com/cockroach-v22.2.9.linux-amd64.tgz",
 :os
 #object[jepsen.os.ubuntu$reify__180 0x7c36db44 "jepsen.os.ubuntu$reify__180@7c36db44"],
 :time-limit 60,
 :recovery-time 60}
[:nemesis-map
 {#object[jepsen.cockroach.nemesis$compose$fn__1206$f_select__1208 0x21079a12 "jepsen.cockroach.nemesis$compose$fn__1206$f_select__1208@21079a12"]
  #object[jepsen.nemesis$reify__4368 0x4ee5b2d9 "jepsen.nemesis$reify__4368@4ee5b2d9"]}]
23:25:10.563 [main] INFO  jepsen.cockroach.runner - Testing
 {:ssh-private-key "/root/.ssh/id_rsa",
 :concurrency 3,
 :db
 #object[jepsen.cockroach$db$reify__120 0x62dbe64e "jepsen.cockroach$db$reify__120@62dbe64e"],
 :name "cockroachdb-register:blank",
 :net
 #object[jepsen.net$reify__4285 0xc3edf4c "jepsen.net$reify__4285@c3edf4c"],
 :client {:tbl-created? #<Atom@36681447: false>, :conn nil},
 :ssh
 {:username "root",
  :password "",
  :strict-host-key-checking false,
  :private-key-path "/root/.ssh/id_rsa"},
 :linearizable false,
 :checker
 #object[jepsen.checker$compose$reify__3952 0xdc4a691 "jepsen.checker$compose$reify__3952@dc4a691"],
 :keyrange #<Atom@bc042d5: {}>,
 :nemesis
 #object[jepsen.nemesis$compose$reify__4401 0x37df14d1 "jepsen.nemesis$compose$reify__4401@37df14d1"],
 :nodes ["n1" "n2" "n3"],
 :test-count 1,
 :generator
 (gen/concat [(gen/synchronize :fresh (gen/timelimit 60 (gen/concat [(gen/on #{:nemesis} (gen/mix [#object[jepsen.cockroach.nemesis$compose$fn$reify__1213 0x70972170 "jepsen.cockroach.nemesis$compose$fn$reify__1213@70972170"]])) (gen/on #object[clojure.core$complement$fn__4611 0x20ab3e3a "clojure.core$complement$fn__4611@20ab3e3a"] #object[jepsen.independent$concurrent_generator$reify__573 0x709ed6f3 "jepsen.independent$concurrent_generator$reify__573@709ed6f3"])]))) (gen/synchronize :fresh (gen/once :pending (gen/log "Nemesis terminating"))) (gen/synchronize :fresh (gen/on #{:nemesis} (gen/concat [#object[jepsen.cockroach.nemesis$compose$fn$reify__1218 0x102c577f "jepsen.cockroach.nemesis$compose$fn$reify__1218@102c577f"]]))) (gen/synchronize :fresh (gen/once :pending (gen/log "Waiting for quiescence"))) (gen/synchronize :fresh (gen/delayfn #object[clojure.core$constantly$fn__4614 0x1fb2d5e "clojure.core$constantly$fn__4614@1fb2d5e"] (gen/gvoid))) (gen/synchronize :fresh (gen/on #object[clojure.core$complement$fn__4611 0x1716e8c5 "clojure.core$complement$fn__4611@1716e8c5"] nil))]),
 :tarball
 "https://binaries.cockroachdb.com/cockroach-v22.2.9.linux-amd64.tgz",
 :os
 #object[jepsen.os.ubuntu$reify__180 0x7c36db44 "jepsen.os.ubuntu$reify__180@7c36db44"],
 :time-limit 60,
 :recovery-time 60,
 :model {:value 0}}
INFO [2023-05-31 23:25:10,633] jepsen test runner - jepsen.core Running test:
 {:ssh-private-key "/root/.ssh/id_rsa",
 :concurrency 3,
 :db
 #object[jepsen.cockroach$db$reify__120 0x62dbe64e "jepsen.cockroach$db$reify__120@62dbe64e"],
 :name "cockroachdb-register:blank",
 :start-time
 #object[org.joda.time.DateTime 0xccf91df "2023-05-31T23:25:10.000+03:00"],
 :net
 #object[jepsen.net$reify__4285 0xc3edf4c "jepsen.net$reify__4285@c3edf4c"],
 :client {:tbl-created? #<Atom@36681447: false>, :conn nil},
 :barrier
 #object[java.util.concurrent.CyclicBarrier 0x12eedfee "java.util.concurrent.CyclicBarrier@12eedfee"],
 :ssh
 {:username "root",
  :password "",
  :strict-host-key-checking false,
  :private-key-path "/root/.ssh/id_rsa"},
 :linearizable false,
 :checker
 #object[jepsen.checker$compose$reify__3952 0xdc4a691 "jepsen.checker$compose$reify__3952@dc4a691"],
 :keyrange #<Atom@bc042d5: {}>,
 :nemesis
 #object[jepsen.nemesis$compose$reify__4401 0x37df14d1 "jepsen.nemesis$compose$reify__4401@37df14d1"],
 :active-histories #<Atom@67514bdd: #{}>,
 :nodes ["n1" "n2" "n3"],
 :test-count 1,
 :generator
 (gen/concat [(gen/synchronize :fresh (gen/timelimit 60 (gen/concat [(gen/on #{:nemesis} (gen/mix [#object[jepsen.cockroach.nemesis$compose$fn$reify__1213 0x70972170 "jepsen.cockroach.nemesis$compose$fn$reify__1213@70972170"]])) (gen/on #object[clojure.core$complement$fn__4611 0x20ab3e3a "clojure.core$complement$fn__4611@20ab3e3a"] #object[jepsen.independent$concurrent_generator$reify__573 0x709ed6f3 "jepsen.independent$concurrent_generator$reify__573@709ed6f3"])]))) (gen/synchronize :fresh (gen/once :pending (gen/log "Nemesis terminating"))) (gen/synchronize :fresh (gen/on #{:nemesis} (gen/concat [#object[jepsen.cockroach.nemesis$compose$fn$reify__1218 0x102c577f "jepsen.cockroach.nemesis$compose$fn$reify__1218@102c577f"]]))) (gen/synchronize :fresh (gen/once :pending (gen/log "Waiting for quiescence"))) (gen/synchronize :fresh (gen/delayfn #object[clojure.core$constantly$fn__4614 0x1fb2d5e "clojure.core$constantly$fn__4614@1fb2d5e"] (gen/gvoid))) (gen/synchronize :fresh (gen/on #object[clojure.core$complement$fn__4611 0x1716e8c5 "clojure.core$complement$fn__4611@1716e8c5"] nil))]),
 :tarball
 "https://binaries.cockroachdb.com/cockroach-v22.2.9.linux-amd64.tgz",
 :os
 #object[jepsen.os.ubuntu$reify__180 0x7c36db44 "jepsen.os.ubuntu$reify__180@7c36db44"],
 :time-limit 60,
 :recovery-time 60,
 :model {:value 0}}
INFO [2023-05-31 23:25:11,202] jepsen node n2 - jepsen.os.ubuntu n2 setting up ubuntu
INFO [2023-05-31 23:25:11,202] jepsen node n1 - jepsen.os.ubuntu n1 setting up ubuntu
INFO [2023-05-31 23:25:11,202] jepsen node n3 - jepsen.os.ubuntu n3 setting up ubuntu
INFO [2023-05-31 23:25:13,228] jepsen test runner - jepsen.db Tearing down DB
INFO [2023-05-31 23:25:22,081] jepsen node n1 - jepsen.cockroach.auto n1 clock reset: 31 May 23:25:22 ntpdate[15684]: step time server 185.125.190.58 offset 0.000033 sec
INFO [2023-05-31 23:25:22,182] jepsen node n2 - jepsen.cockroach.auto n2 clock reset: 31 May 23:25:22 ntpdate[21054]: step time server 185.125.190.57 offset 0.002106 sec
INFO [2023-05-31 23:25:22,183] jepsen node n1 - jepsen.cockroach.auto n1 Cockroach killed.
INFO [2023-05-31 23:25:22,183] jepsen node n1 - jepsen.cockroach n1 Erasing the store...
INFO [2023-05-31 23:25:22,282] jepsen node n3 - jepsen.cockroach.auto n3 clock reset: 31 May 23:25:22 ntpdate[4002459]: step time server 185.125.190.57 offset -0.000294 sec
INFO [2023-05-31 23:25:22,282] jepsen node n2 - jepsen.cockroach.auto n2 Cockroach killed.
INFO [2023-05-31 23:25:22,282] jepsen node n2 - jepsen.cockroach n2 Erasing the store...
INFO [2023-05-31 23:25:22,284] jepsen node n1 - jepsen.cockroach n1 Stopping tcpdump...
INFO [2023-05-31 23:25:22,383] jepsen node n2 - jepsen.cockroach n2 Stopping tcpdump...
INFO [2023-05-31 23:25:22,385] jepsen node n1 - jepsen.cockroach n1 Clearing the logs...
INFO [2023-05-31 23:25:22,482] jepsen node n3 - jepsen.cockroach.auto n3 Cockroach killed.
INFO [2023-05-31 23:25:22,482] jepsen node n3 - jepsen.cockroach n3 Erasing the store...
INFO [2023-05-31 23:25:22,484] jepsen node n2 - jepsen.cockroach n2 Clearing the logs...
INFO [2023-05-31 23:25:22,683] jepsen node n3 - jepsen.cockroach n3 Stopping tcpdump...
INFO [2023-05-31 23:25:22,884] jepsen node n3 - jepsen.cockroach n3 Clearing the logs...
INFO [2023-05-31 23:25:24,689] jepsen test runner - jepsen.db Setting up DB
INFO [2023-05-31 23:25:24,717] jepsen node n1 - jepsen.cockroach Wrote /.autodirect/mtrswgwork/rwiener/workspace/jepsen/cockroachdb/store/cockroachdb-register:blank/20230531T232510.000+0300/jepsen-version.txt
INFO [2023-05-31 23:25:30,121] jepsen node n2 - jepsen.cockroach.auto n2 Cockroach installed
INFO [2023-05-31 23:25:30,260] jepsen node n1 - jepsen.cockroach.auto n1 Cockroach installed
INFO [2023-05-31 23:25:33,675] jepsen node n3 - jepsen.cockroach.auto n3 Cockroach installed
INFO [2023-05-31 23:25:38,695] jepsen node n1 - jepsen.cockroach.auto n1 clock reset: 31 May 23:25:38 ntpdate[15843]: step time server 185.125.190.58 offset 0.000005 sec
INFO [2023-05-31 23:25:38,826] jepsen node n2 - jepsen.cockroach.auto n2 clock reset: 31 May 23:25:38 ntpdate[21214]: step time server 185.125.190.57 offset 0.000012 sec
INFO [2023-05-31 23:25:42,580] jepsen node n3 - jepsen.cockroach.auto n3 clock reset: 31 May 23:25:42 ntpdate[4002613]: step time server 185.125.190.57 offset 0.000019 sec
INFO [2023-05-31 23:25:42,682] jepsen node n1 - jepsen.cockroach.auto n1 Starting CockroachDB...
INFO [2023-05-31 23:25:42,687] jepsen node n1 - jepsen.control Host: n1 arg: {:cmd sudo -S -u cockroach bash -c "cd /; env COCKROACH_LINEARIZABLE=false COCKROACH_MAX_OFFSET=250ms start-stop-daemon --start --background --make-pidfile --remove-pidfile --pidfile /opt/cockroach/pid --no-close --chuid cockroach --chdir /opt/cockroach --exec /opt/cockroach/cockroach -- start --insecure  --logtostderr >> /opt/cockroach/logs/cockroach.stderr 2>&1", :in 
}
INFO [2023-05-31 23:25:42,787] jepsen node n1 - jepsen.cockroach.auto n1 Cockroach started
INFO [2023-05-31 23:25:47,888] jepsen node n2 - jepsen.cockroach.auto n2 Starting packet capture (filtering on 10.210.12.41 )...
INFO [2023-05-31 23:25:47,888] jepsen node n3 - jepsen.cockroach.auto n3 Starting packet capture (filtering on 10.210.12.41 )...
INFO [2023-05-31 23:25:47,888] jepsen node n1 - jepsen.cockroach.auto n1 Starting packet capture (filtering on 10.210.12.41 )...
INFO [2023-05-31 23:25:48,890] jepsen node n2 - jepsen.cockroach.auto n2 Starting CockroachDB...
INFO [2023-05-31 23:25:48,891] jepsen node n2 - jepsen.control Host: n2 arg: {:cmd sudo -S -u cockroach bash -c "cd /; env COCKROACH_LINEARIZABLE=false COCKROACH_MAX_OFFSET=250ms start-stop-daemon --start --background --make-pidfile --remove-pidfile --pidfile /opt/cockroach/pid --no-close --chuid cockroach --chdir /opt/cockroach --exec /opt/cockroach/cockroach -- start --insecure --join=n1,n3 --logtostderr >> /opt/cockroach/logs/cockroach.stderr 2>&1", :in 
}
INFO [2023-05-31 23:25:48,991] jepsen node n2 - jepsen.cockroach.auto n2 Cockroach started
INFO [2023-05-31 23:25:49,090] jepsen node n3 - jepsen.cockroach.auto n3 Starting CockroachDB...
INFO [2023-05-31 23:25:49,090] jepsen node n3 - jepsen.control Host: n3 arg: {:cmd sudo -S -u cockroach bash -c "cd /; env COCKROACH_LINEARIZABLE=false COCKROACH_MAX_OFFSET=250ms start-stop-daemon --start --background --make-pidfile --remove-pidfile --pidfile /opt/cockroach/pid --no-close --chuid cockroach --chdir /opt/cockroach --exec /opt/cockroach/cockroach -- start --insecure --join=n1,n2 --logtostderr >> /opt/cockroach/logs/cockroach.stderr 2>&1", :in 
}
INFO [2023-05-31 23:25:49,291] jepsen node n3 - jepsen.cockroach.auto n3 Cockroach started
INFO [2023-05-31 23:25:54,921] jepsen test runner - jepsen.core Snarfing log files
INFO [2023-05-31 23:25:54,924] jepsen node n2 - jepsen.core downloading /opt/cockroach/logs/cockroach.stderr to cockroach.stderr
INFO [2023-05-31 23:25:54,924] jepsen node n3 - jepsen.core downloading /opt/cockroach/logs/cockroach.stderr to cockroach.stderr
INFO [2023-05-31 23:25:54,924] jepsen node n1 - jepsen.core downloading /opt/cockroach/logs/cockroach.stderr to cockroach.stderr
INFO [2023-05-31 23:25:54,975] jepsen node n2 - jepsen.core downloading /opt/cockroach/logs/version.txt to version.txt
INFO [2023-05-31 23:25:54,978] jepsen node n1 - jepsen.core downloading /opt/cockroach/logs/version.txt to version.txt
INFO [2023-05-31 23:25:54,997] jepsen node n3 - jepsen.core downloading /opt/cockroach/logs/version.txt to version.txt
INFO [2023-05-31 23:25:55,015] jepsen node n2 - jepsen.core downloading /opt/cockroach/logs/trace.pcap to trace.pcap
INFO [2023-05-31 23:25:55,022] jepsen node n1 - jepsen.core downloading /opt/cockroach/logs/trace.pcap to trace.pcap
INFO [2023-05-31 23:25:55,063] jepsen node n3 - jepsen.core downloading /opt/cockroach/logs/trace.pcap to trace.pcap
INFO [2023-05-31 23:26:02,147] jepsen node n2 - jepsen.cockroach.auto n2 clock reset: 31 May 23:26:02 ntpdate[21335]: step time server 185.125.190.57 offset 0.000028 sec
INFO [2023-05-31 23:26:02,248] jepsen node n2 - jepsen.cockroach.auto n2 Cockroach killed.
INFO [2023-05-31 23:26:02,248] jepsen node n2 - jepsen.cockroach n2 Erasing the store...
INFO [2023-05-31 23:26:02,348] jepsen node n2 - jepsen.cockroach n2 Stopping tcpdump...
INFO [2023-05-31 23:26:02,449] jepsen node n2 - jepsen.cockroach n2 Clearing the logs...
INFO [2023-05-31 23:26:03,644] jepsen node n1 - jepsen.cockroach.auto n1 clock reset: 31 May 23:26:03 ntpdate[15922]: step time server 185.125.190.58 offset 0.000001 sec
INFO [2023-05-31 23:26:03,744] jepsen node n1 - jepsen.cockroach.auto n1 Cockroach killed.
INFO [2023-05-31 23:26:03,745] jepsen node n1 - jepsen.cockroach n1 Erasing the store...
INFO [2023-05-31 23:26:03,945] jepsen node n1 - jepsen.cockroach n1 Stopping tcpdump...
INFO [2023-05-31 23:26:04,046] jepsen node n1 - jepsen.cockroach n1 Clearing the logs...
INFO [2023-05-31 23:26:04,244] jepsen node n3 - jepsen.cockroach.auto n3 clock reset: 31 May 23:26:04 ntpdate[4002714]: step time server 185.125.190.57 offset 0.000019 sec
INFO [2023-05-31 23:26:04,445] jepsen node n3 - jepsen.cockroach.auto n3 Cockroach killed.
INFO [2023-05-31 23:26:04,445] jepsen node n3 - jepsen.cockroach n3 Erasing the store...
INFO [2023-05-31 23:26:04,645] jepsen node n3 - jepsen.cockroach n3 Stopping tcpdump...
INFO [2023-05-31 23:26:04,846] jepsen node n3 - jepsen.cockroach n3 Clearing the logs...
ERROR [2023-05-31 23:26:06,676] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
java.util.concurrent.ExecutionException: java.lang.RuntimeException: sudo -S -u cockroach bash -c "cd /opt/cockroach; echo \"{range_min_bytes: 1024, range_max_bytes: 1048576}
\" | /opt/cockroach/cockroach zone set --insecure --file=- .default" returned non-zero exit status 1 on n1. STDOUT:
STDERR:
ERROR: unknown command "zone" for "cockroach"

Did you mean this?
        node
Failed running "cockroach"

        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_362]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_362]
        at clojure.core$deref_future.invokeStatic(core.clj:2208) ~[clojure-1.8.0.jar:na]
        at clojure.core$future_call$reify__6962.deref(core.clj:6688) ~[clojure-1.8.0.jar:na]
        at clojure.core$deref.invokeStatic(core.clj:2228) ~[clojure-1.8.0.jar:na]
        at clojure.core$deref.invoke(core.clj:2214) ~[clojure-1.8.0.jar:na]
        at clojure.core$map$fn__4785.invoke(core.clj:2644) ~[clojure-1.8.0.jar:na]
        at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.8.0.jar:na]
        at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.8.0.jar:na]
        at clojure.lang.RT.seq(RT.java:521) ~[clojure-1.8.0.jar:na]
        at clojure.core$seq__4357.invokeStatic(core.clj:137) ~[clojure-1.8.0.jar:na]
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24) ~[clojure-1.8.0.jar:na]
        at clojure.core.protocols$fn__6738.invokeStatic(protocols.clj:75) ~[clojure-1.8.0.jar:na]
        at clojure.core.protocols$fn__6738.invoke(protocols.clj:75) ~[clojure-1.8.0.jar:na]
        at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13) ~[clojure-1.8.0.jar:na]
        at clojure.core$reduce.invokeStatic(core.clj:6545) ~[clojure-1.8.0.jar:na]
        at clojure.core$into.invokeStatic(core.clj:6610) ~[clojure-1.8.0.jar:na]
        at clojure.core$into.invoke(core.clj:6604) ~[clojure-1.8.0.jar:na]
        at jepsen.control$on_nodes.invokeStatic(control.clj:373) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
        at jepsen.control$on_nodes.invoke(control.clj:357) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
        at jepsen.control$on_nodes.invokeStatic(control.clj:362) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
        at jepsen.control$on_nodes.invoke(control.clj:357) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
        at jepsen.db$cycle_BANG_$fn__2210.invoke(db.clj:45) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
        at jepsen.db$cycle_BANG_.invokeStatic(db.clj:42) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
        at jepsen.db$cycle_BANG_.invoke(db.clj:28) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
        at jepsen.core$run_BANG_$fn__4663$fn__4666.invoke(core.clj:607) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
        at jepsen.core$run_BANG_$fn__4663.invoke(core.clj:595) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
        at jepsen.core$run_BANG_.invokeStatic(core.clj:576) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
        at jepsen.core$run_BANG_.invoke(core.clj:522) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
        at jepsen.cockroach.runner$test_cmd$fn__2374.invoke(runner.clj:131) ~[classes/:na]
        at jepsen.cli$run_BANG_.invokeStatic(cli.clj:275) [jepsen-0.1.9-SNAPSHOT.jar:na]
        at jepsen.cli$run_BANG_.invoke(cli.clj:205) [jepsen-0.1.9-SNAPSHOT.jar:na]
        at jepsen.cockroach.runner$_main.invokeStatic(runner.clj:142) [classes/:na]
        at jepsen.cockroach.runner$_main.doInvoke(runner.clj:140) [classes/:na]
        at clojure.lang.RestFn.invoke(RestFn.java:3894) [clojure-1.8.0.jar:na]
        at clojure.lang.Var.invoke(Var.java:676) [clojure-1.8.0.jar:na]
        at user$eval5.invokeStatic(form-init4960369422009488257.clj:1) [na:na]
        at user$eval5.invoke(form-init4960369422009488257.clj:1) [na:na]
        at clojure.lang.Compiler.eval(Compiler.java:6927) [clojure-1.8.0.jar:na]
        at clojure.lang.Compiler.eval(Compiler.java:6917) [clojure-1.8.0.jar:na]
        at clojure.lang.Compiler.load(Compiler.java:7379) [clojure-1.8.0.jar:na]
        at clojure.lang.Compiler.loadFile(Compiler.java:7317) [clojure-1.8.0.jar:na]
        at clojure.main$load_script.invokeStatic(main.clj:275) [clojure-1.8.0.jar:na]
        at clojure.main$init_opt.invokeStatic(main.clj:277) [clojure-1.8.0.jar:na]
        at clojure.main$init_opt.invoke(main.clj:277) [clojure-1.8.0.jar:na]
        at clojure.main$initialize.invokeStatic(main.clj:308) [clojure-1.8.0.jar:na]
        at clojure.main$null_opt.invokeStatic(main.clj:342) [clojure-1.8.0.jar:na]
        at clojure.main$null_opt.invoke(main.clj:339) [clojure-1.8.0.jar:na]
        at clojure.main$main.invokeStatic(main.clj:421) [clojure-1.8.0.jar:na]
        at clojure.main$main.doInvoke(main.clj:384) [clojure-1.8.0.jar:na]
        at clojure.lang.RestFn.invoke(RestFn.java:421) [clojure-1.8.0.jar:na]
        at clojure.lang.Var.invoke(Var.java:383) [clojure-1.8.0.jar:na]
        at clojure.lang.AFn.applyToHelper(AFn.java:156) [clojure-1.8.0.jar:na]
        at clojure.lang.Var.applyTo(Var.java:700) [clojure-1.8.0.jar:na]
        at clojure.main.main(main.java:37) [clojure-1.8.0.jar:na]
Caused by: java.lang.RuntimeException: sudo -S -u cockroach bash -c "cd /opt/cockroach; echo \"{range_min_bytes: 1024, range_max_bytes: 1048576}
\" | /opt/cockroach/cockroach zone set --insecure --file=- .default" returned non-zero exit status 1 on n1. STDOUT:

```

**Comment by aphyr** [comment]
That test was written for cockroachdb beta 20160829, which is six years old. If you want it to work on Cockroach today, you're gonna have to find out all the ways Cockroach has changed and update the test code accordingly--I'm afraid I can't really help with that. 

https://github.com/jepsen-io/jepsen/blob/4d402bae4a216632a897be8f0795a6eff0462837/cockroachdb/src/jepsen/cockroach/runner.clj#L83

**Comment by rafiw** [comment]
https://forum.cockroachlabs.com/t/error-running-jepsen-against-a-local-cluster/5938/5
